### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Orange15** [searchivarius/nmslib#116]
CentOS 6.6 / gcc 4.9.3 / Intel(R) Xeon(R) CPU E5-2630 v3
/tmp/ccY4AmR9.s: Assembler messages:
/tmp/ccY4AmR9.s:402: Error: suffix or operands invalid for `vbroadcastsd'
make[2]: **\* [src/CMakeFiles/NonMetricSpaceLib.dir/utils.cc.o] Error 1
make[1]: **\* [src/CMakeFiles/NonMetricSpaceLib.dir/all] Error 2

**Comment by searchivarius** [comment]
vbroadcastsd wow... could you replace -march=native in ``similarity_searchCMakeLists.txt`` with -march=core-avx2 and rebuild everything?
**you will need to delete all the caches first** 
```
cd similarity_search
rm -rf `find . -name CMakeFiles` CMakeCache.txt
cmake .
```
Thanks!

**Comment by Orange15** [comment]
thanks, but it is the same problem.

**Comment by searchivarius** [comment]
Uuups, this vbroadcastsd is actually an AVX command.
and what if you have -msse4.2 instead ?
Please, make sure you replace it everywhere.
Do you run it on your machine, or somewhere in the cloud? I wonder what is the easy way for me to reproduce this. Interestingly, the command that the assembler complains about seems to be generated by gcc, i.e., we don't use use sort of the command.

**Comment by searchivarius** [comment]
can't reproduce
