### ISSUE TITLE
HNSW post parameter & heuristics useful for clustering

### ISSUE THREAD

**Issue by bittremieux** [searchivarius/nmslib#121]
First off, thank you for your amazing effort in developing the nmslib.

I've previously used Annoy for some ANN searching, but I'm trying out the HNSW graph now because of its improved performance.
Unfortunately, although your documentation is very clear and comprehensive, it doesn't seem to mention the `post` parameter for the HNSW graph.

Judging from the erikbern/ann-benchmarks code, setting `post` to either `0` or `2` has a big influence on the `ef` parameter. How should I interpret the `post` parameter to tune it for optimal performance at a high recall?

**Leo's additional comment:**
We also have an undocumented define in hnsw.cc, whose change to 1 may help in the case of clustered data:
```#define EXTEND_USE_EXTENDED_NEIGHB_AT_CONSTR (0)```
We need to make it a param and document as well.

**Comment by yurymalkov** [comment]
Hello @bittremieux, thank you for the kind words!

The `post=2` adds an additional post-processing step to symmetrize the index. It is not documented yet in nmslib and do not presented in the paper on HNSW. In short, two indexes is build with different order of the data(direct and reverse), with following union of the produced connections. It does not affect directly the query time parameters, such as `ef`.

On overall, it leads to a roughly twice as long construction time, while in the end adding extra search performance at high recalls (up to several tens of percent in tests on 1M sift at ~0.999 recall, the gain smaller for less recall). So if you want to get maximum performance at search you should use `post=2`.

**Comment by bittremieux** [comment]
Ok great, thank you for the explanation.

**Comment by searchivarius** [comment]
We will sure update the docs in some of the upcoming releases.
Thanks!

**Comment by searchivarius** [comment]
Gathering all such tickets under the umbrella of #156
