### ISSUE TITLE
Best method for binary features

### ISSUE THREAD

**Issue by ajkl** [searchivarius/nmslib#123]
Are there any guidelines on techniques well suited for binary feature vectors ?
Will SWG with cosine similarity still work with binary feature vector ?

**Comment by searchivarius** [comment]
Hi @ajkl 

I don't know what SWG is.

If this is a meaningful kNN problem, then it will likely be fine.
If you have something like an iris recognition problem where irisis of two different eyes (even from the same person), are at nearly equal distances from each other, then standard kNN techniques won't work and your only resort is near-duplicate detection.

**Comment by ajkl** [comment]
My bad, I meant SW-graph. So you are saying SW-graph should still be fine ?
Is there an example where `bit_hamming` makes sense for distance type ? Didnt find any documentation on a real usecase of `bit_hamming`. I tried `bit_hamming` with SW-graph and it doesnt seem to work.

**Comment by searchivarius** [comment]
What is the data set that you play with?

**Comment by ajkl** [comment]
Binary features somewhat similar to this http://www.cs.ubc.ca/~lowe/papers/12mujaCRV.pdf So its like 2048 or 4096 dimensional binary features.

**Comment by searchivarius** [comment]
At least BRIEF and ORB used in the cited paper are not very high-dimensional (128 and 256), only BRISK is. Muja and Lowe seem to claim that these descriptors have clusters! I would think that in the presence of clusters SW-graph or HNSW should work. However, if you got from 128-256 dimensions to 2048-4096 dimensions things may change. 

**Did you try to plot the histogram of distance between two randomly selected points and compare it against the histogram of distances from a point to its respective nearest neighbor?**

**Comment by ajkl** [comment]
No I have not tried that, can try to plot that. I guess that will provide an indication of how far it is from random?
 I didnt try this plot but I ran SW-Graph and it seems to work well with binary features. Just wanted to see if `nmslib` has specialized techniques like the multi-hierarchy clustering trees in the above paper which work specifically well with binary features.

**Comment by searchivarius** [comment]
**No I have not tried that, can try to plot that. I guess that will provide an indication of how far it is from random?**
Right...
**Just wanted to see if nmslib has specialized techniques like the multi-hierarchy clustering trees in the above paper which work specifically well with binary features.**
No multi-hierarchy trees. One reason, why I didn't added them, b/c in my experience if you have clusters, than SW-graph (or HNSW) should work really well. Clusters is a relatively easy case.

**Comment by searchivarius** [comment]
But if you have binary features of dimensionality 1024 with bits generated randomly, this is a very unfortunate situtation. The only exception is when your queries are obtained by a small distortion of data set points. Then you can do a near-duplicate detection (which is what they do for iris recognition).

**Comment by ajkl** [comment]
No no, they are not generated randomly. They are learnt and have cluster information. Good to know that SW-Graph works better that multi-hierarchy trees if there is good enough cluster information within the binary features. I will stick to SW-Graph then. Thanks for the help!
