### ISSUE TITLE
Could HNSW and SW-grap support incremental indexing?

### ISSUE THREAD

**Issue by agangzz** [searchivarius/nmslib#124]
As I know, the indexing process of HNSW and SW-grap algorithm is rather expensive. When we want to add new data to HNSW/SW-grap (this case may be more frequently), we must rebuild indexing which is time consuming. 

So If HNSW and SW-grap can support incremental indexing, it may be more attractive efficient.

(  It is worth mentioning that the features of index save/load is very useful. )

**Comment by searchivarius** [comment]
Hi, yes we have it in plans, see issue #73 . However, it will require a lot of changes to the library, so I don't know when it'll be done.

**Comment by searchivarius** [comment]
Currently, there is an experimental support for incremental addition and/or deletion (all should be done in batches), but it requires using C++ directly.
