### ISSUE TITLE
Save/Load of SW-graph index

### ISSUE THREAD

**Issue by ajkl** [searchivarius/nmslib#126]
I saw the index updating after its built is in plans. Till that sees the light of the day can I do a work around like this -
```nmslib_vector.addDataPoint  # for the first set of data
nmslib_vector.createIndex  # for the first set of data```

and then with new items coming in update the index with -
```nmslib_vector.addDataPoint  # add new data point/s
nmslib_vector.createIndex  # update old index```

Will this work ?

**Comment by searchivarius** [comment]
No, createIndex should be called only once, after the data set is loaded.

**Comment by ajkl** [comment]
The second createIndex will generate the index from scratch though (if not update)? That would at least save re-adding all the datapoints while reindexing. Thoughts ?

**Comment by searchivarius** [comment]
It wasn't designed to work with a second createIndex call. Will it work? Who knows. Re-reading data points takes short time compared to building the index.

**Comment by ajkl** [comment]
Fair enough. I read the SW-graph paper and the algorithm seems to support addition of data naturally, too bad if we cant take advantage of it. I will explore the SW-graph code ...

**Comment by searchivarius** [comment]
It's rather easy to extend if you through away all the library contents, but SW-graph. However, changing API in a way that doesn't break things is hard.

**Comment by ajkl** [comment]
I agree, I guessed that would be the reason why it was not supported. Will fork it and give it a shot.
