### ISSUE TITLE
NN-descent algorithm don't support save/load index?

### ISSUE THREAD

**Issue by agangzz** [searchivarius/nmslib#127]
From my evaluation of my testset, the performance (such as precision, search speed) of  NN-descent algorithm is similar. When I further use, I found that the NN-descent algorithm don't support save/load index feature.

So do nmslib have plan to support save/load index feature for NN-descent algorithm?

Thanks.

**Comment by searchivarius** [comment]
It's an old experimental version that was created before k-graph was open-sourced. So, definitely no saving index of this one. The current version of k-graph is much butter, but I believe that either SW-graph or HNSW should be either outperforming k-graph or have a comparable performance.
