### ISSUE TITLE
Can't load index?

### ISSUE THREAD

**Issue by zommerfelds** [searchivarius/nmslib#128]
Hi, this might me more of a question than problem in the library.
I have created an index with NAPP and saved it using `saveIndex`. However when I load it with `loadIndex` I get the following error:

`Check failed: A previously saved index is apparently used with a different data set, a different data set split, and/or a different gold standard file! (detected an object index >= #of data points`

Am I doing something wrong?

Thanks for the help.

EDIT: The message doesn't make sense to me because I'm not "using the index with a data set", I'm just loading it.

EDIT2: I'm using the Python interface.

**Comment by searchivarius** [comment]
Hi, this is not a true index in the sense that it doesn't memorize the data set. So, you have to load the same data set first, then you load the (meta)index.

**Comment by zommerfelds** [comment]
Oh I see, thanks!
Is there a way to load vectors in parallel? For my data set loading takes 1.5h on a 32 cores machine. The process doesn't seem I/O bound (at least in Python). Depending on the parameters, indexing is faster than loading because I have many cores available. I'm loading sparse vectors using the generic loading function that takes a string as input.
I appreciate your time!

**Comment by searchivarius** [comment]
How many data points do you have?

**Comment by zommerfelds** [comment]
4.5M with each having an average of 1000 non-zero entries.
Is the method `nmslib_generic.addDataPoint` thread safe?

**Comment by searchivarius** [comment]
This is way too long for 4.5M. No addDataPoint is not thread-safe. But are you sure it's not Python? How long does it take to read the data file without calling addDataPoint?

**Comment by zommerfelds** [comment]
All I'm doing is decompressing (gzip) some text files and doing a few string transformations, but I'm going to try it out right now and let you know in a few minutes.

**Comment by searchivarius** [comment]
BTW, do you use generic python bindings or vector ones?

**Comment by searchivarius** [comment]
Also, although this is not yet document properly, for sparse spaces and NAPP you need to generate pivots randomly. Otherwise, performance is bad. Citing our paper: http://boytsov.info/pubs/cikm2016.pdf
```
Tellez et al. [63] use pivots randomly sampled from the data set,
but we find that for sparse data such as TF×IDF vectors substantially
shorter retrieval times—sometimes by orders of magnitude—can be
obtained by using a special pivot generation algorithm. Specifically,
pivots are generated as pseudo-documents containing K entries
sampled from the set of M most frequent words (in our setup K =
1000 and M = 50000).
```

**Comment by zommerfelds** [comment]
Thanks for the citation. I've actually seen this, but I've been too lazy so far to look into the details of how to do that. Maybe it's time now ;)

You were right about Python Without calling `addDataPoint` the loading is still pretty slow (~1h estimate). Ungzipping was done on separate cores so it shouldn't affect the throughput. I'll try to optimize my loading code. Thanks for the help!

I use the generic bindings. Maybe I didn't look enough but the `vect` bindings didn't seem to support sparse input. Is this true?

**Comment by zommerfelds** [comment]
I parallelized the Python string processing and now it's working much faster. Thanks for the great library and support!

**Comment by zommerfelds** [comment]
Actually no, sorry. Once I added back the call to `addDataPoint` it is now the bottleneck. It might be the speed of the Python processing on the generic bindings. It would still take ~1h to load the vectors.

**Comment by searchivarius** [comment]
Aargh, loading data isn't our forte. However, after a bit of thought I came to a conclusion that it is trivial to make this function thread-safe. Could you try the attached version? Don't forget to re-install SO-file, if you installed it previously. I guess you can play with a small data set first (say 1/5 th of the size) to see if there's a difference.
[nmslib_generic.cc.zip](https://github.com/searchivarius/nmslib/files/474759/nmslib_generic.cc.zip)

**Comment by searchivarius** [comment]
PS: it's correct to use generic bindings for sparse vectors. A good question if we could avoid this conversion from the string... At the very least, I will try to make it faster.

**Comment by zommerfelds** [comment]
Thanks I'll try it out now!

**Comment by zommerfelds** [comment]
Hi again. I was using multiprocessing (multiprocessing.Pool) but that won't work because each process will end up with separate indices. Then I tried multithreading (multiprocessing.pool.ThreadPool) but the performance did not improve. This could because of the GIL (so the code that I had previously parallelized is no longer running in parallel and the bottleneck moved from the library to my code). I have a limited understand on the low level of CPython but it seems like a reasonable explanation to me.

Maybe a combination of threads and processes could solve the issue but this seems too complex to me just for loading vectors.

**Comment by searchivarius** [comment]
Hi, thank you for trying. The updated version of bindings is actually trying to realease GIL. But I don't know if this works or not. Why do you think your code may be affected by GIL?

**Comment by zommerfelds** [comment]
It is affected by the GIL because I want to parallelize the code that reads and converts the vector format:
```
id_str, indices_str, values_str = line.split(';')
id = int(id_str)
indices = indices_str.split(',')
values = values_str.split(',')
string = ' '.join('{} {}'.format(i, v) for i, v in zip(indices, values))
```

I was a bit surprised that this is so slow so I simply parallelized it with `multiprocessing.Pool`. This made it much faster. But with threading your library seems to get faster but my code loses the speedup.

Either way, I think you improved your library with that change. Now it is really a pure Python problem that you can't really do much about I think.

**Comment by searchivarius** [comment]
Well, this code cannot be run in parallel AFAIK due to GIL. However, if you combine it with IO and a call to unzip contents, this may run in parallel if uncompressing code releases GIL.
PS: We really need to implement reading from binary formats.

**Comment by zommerfelds** [comment]
Yeah, binary sounds great 👍 Thanks for all the help! You can close this issue if you want.

If I may, I have an unrelated question: we are actually building a full k-NN graph with your library, rather than just doing a few specific searches. So we load the data twice, once to index and once to query. Is there any kind of parameters/tricks you suggest for speeding up this case?

Also thanks for the tip in your paper about the special pivot generation algorithm. I will give it a shot later.

**Comment by searchivarius** [comment]
You are welcome. I will keep the issue and reassing to some of the future releases.

Regarding the full k-NN graph. Why do you load things a second time? Why don't you start querying right after the index is created?

Regarding parameters: if you use NAPP, do make sure you play with proper generation of pivots. There are parameters to be tuned: numPivot (usually some reasonably large number), numPivotIndex number of pivots to index, and numPivotSearch, which means the minimum number of pivots shared between the query and a data point to be retrieved.  But you probably need to tune parameters.

If you generate pivots as explained in the paper, some reasonable parameters could be: 
```
numPivot=4000,numPivot=100,numPivot=6..12
```

However, because your documents are quite long, you might need smaller number of pivots overall. So, something like:
```
numPivot=2000,numPivot=50,numPivot=3..6
```
may work as well.

Also, you can generate k-NN graphs using HNSW or SW-graph. Yet, unfortunately, there would be no way to extract such a graph efficiently :-(

**Comment by zommerfelds** [comment]
Sorry, by loading I meant rereading the data from disk to generate query vectors (so I don't have to keep them in memory additionally to NMSLIB). I still keep the index and everything NMSLIB creates in memory though. I have to check if I have enough memory, if so of course I don't need to read twice. But this part is less problematic because I can spawn separate processes and format the data faster.

Thanks for the info about parameters. Using the default parameters (512, 32, 8) the full k-NN would take way too long on a 32 core machine (I don't remember but over a month). So I would rather have to reduce accuracy. However I haven't tried the engineered pivots yet.

**Comment by searchivarius** [comment]
Hi Cristian,

Would you try the version that can extract data points stored in memory allocated by NMSLIB? See the attached zip. It also has an updated Python example. **Make sure you pass the object index**
[nmslib_generic.cc.zip](https://github.com/searchivarius/nmslib/files/475286/nmslib_generic.cc.zip)
, i.e., a zero-based position in the data array, not an id, which may be different.

Please, also note that querying can be run in a multi-threaded mode. If you need to call GetDataSetQty, make sure you do before you start querying. This thing doesn't release the GIL. But GetDataPoint releases GIL for a while (though not for the complete duration of execution).

**Comment by searchivarius** [comment]
Sorry, please use this zip: 
[nmslib_generic.cc.zip](https://github.com/searchivarius/nmslib/files/475293/nmslib_generic.cc.zip)

**Comment by zommerfelds** [comment]
Thanks for this! I will hopefully test it before the end of the week, but can't guarantee.

**Comment by searchivarius** [comment]
No rush, but, please, let me know about results. If this works for you, I will update the repo.

**Comment by zommerfelds** [comment]
Hi again.
I'd like to report some first results for an experiment I did. This is without using your new code yet. Let me know if you have a different preference for communication or if this issue is getting bloated.

I have run NAPP on 10% my data set with and without external pivot generation. Without the initial loading time I got:

Method | Params | Time | % top K | diff sum sim
--- | --- | --- | --- | ---
NAPP without generated pivots | (32, 8, 4) | 406.1 min | 79.6 | 0.0114
NAPP with generated pivots | (32, 8, 4) | 148.5 min | 39.6 | 0.0493

The tuples mean (numPivot, numPivotIndex, numPivotSearch). The first score is how many elements are in the brute force k-NN (higher is better) and the second is the sum of similarities of brute force minus the sum of similarities of the approximation (lower is better).

The generated pivots were significantly faster, but it seems to come with a price of accuracy. I'm going to try out some other settings.

**Comment by searchivarius** [comment]
Hi,

le'ts keep it here until I setup some forum. BTW, which one do you think is good, gitter or something else?

Answering your question.
1) Frequent means term frequency. I include only indexed terms, so stop words should be excluded. The co-author who invented this tried different variants and found that focusing on high-IDF values doesn't help.
2) Sampling is **without** replacement, below's the link to Python code that generate pivots. It assumes that terms are **sorted in the order of term frequency**. In other words, 0 is the most frequent, 1 is the next most frequent and so on... Also, note that you need to generate pivots in slightly different format:
https://github.com/oaqa/knn4qa/blob/master/scripts/nmslib/gen_pivots_multifield.py#L83

**Comment by searchivarius** [comment]
Regarding your query stat: is it single-thread? So, if In understand it correctly it's about 450K queries answered in 400*60 seconds, or 18 queries per second. A question is whether it's single or multi-thread?

**Comment by searchivarius** [comment]
PS: if term IDs are already sorted by frequency, you can use the following simple script to generate pivots:

[gen_pivots_sparse_cosine.py.zip](https://github.com/searchivarius/nmslib/files/488637/gen_pivots_sparse_cosine.py.zip)

**Comment by zommerfelds** [comment]
It seems like I'm generating the pivots the same way.
I just added one more row to the table in my previous post. It doesn't seem that the generated external pivots are helping in this case.

I run the test on a 32 cores machine and it was running on multiple processes (100% usage). So that makes 450000/(400*60*32)=0.59 queries per second per core. However, this timing includes reading the vectors again. I'm just working on adding your new `GetDataPoint` function.

**Comment by searchivarius** [comment]
Interesting, I haven't seen yet a dataser where this didn't work. Would you mind sharing say 1m subset so that I can have a look? Better via e mail leo@boytsov.info 
Please specify which distance you use 
Thank you!
