### ISSUE TITLE
Where are the query time results for HNSW?

### ISSUE THREAD

**Issue by nliu86** [searchivarius/nmslib#129]
After going through all the documentation, I was not able to figure out where the query time results are for HNSW. It should have a file which lists all the K-NNs for the queries I'm interested.

Below are the two commands I used. The first one is for creating index. The second is for querying.

/Users/xxx/nmslib-1.5.3/similarity_search/release/experiment \
--distType float --spaceType l2 \
--knn 100 \
--dataFile ../head.num.txt --outFilePrefix result \
--queryFile ../head.num.txt_testset \
--cachePrefixGS hnsw \
--method hnsw \
--createIndex M=32,efConstruction=400,searchMethod=4 \
--queryTimeParams efSearch=100 \
--saveIndex hnsw_index \
--logFile logIndex.txt \
--threadTestQty 40

/Users/xxx/nmslib-1.5.3/similarity_search/release/experiment \
--distType float --spaceType l2 \
--knn 100 \
--dataFile ../head.num.txt --outFilePrefix result \
--queryFile ../head.num.txt_testset \
--method hnsw \
--queryTimeParams efSearch=100 \
--loadIndex hnsw_index \
--logFile logQuery.txt \
--threadTestQty 40

Below are the files generated:

-0-xxxx@xxxx:~/xxxxx/result $ ls -alt
total 98592
-rw-r--r-- 1 xxxx xxxx    27681 Sep 15 21:14 logQuery.txt
-rw-r--r-- 1 xxxx xxxx      331 Sep 15 21:14 result_K=100.dat
-rw-r--r-- 1 xxxx xxxx      831 Sep 15 21:14 result_K=100.rep
drwxr-xr-x 2 xxxx xxxx     4096 Sep 15 21:14 .
-rw-r--r-- 1 xxxx xxxx    29233 Sep 15 21:10 logIndex.txt
-rw-r--r-- 1 xxxx xxxx  1200008 Sep 15 21:10 hnsw_data.bin
-rw-r--r-- 1 xxxx xxxx 99674820 Sep 15 21:10 hnsw_index
-rw-r--r-- 1 xxxx xxxx     4082 Sep 15 21:10 hnsw_ctrl.txt
drwxr-xr-x 3 xxxx xxxx     4096 Sep 14 22:31 ..

**Comment by searchivarius** [comment]
Hi, please, check the files result_K=100.dat and result_K=100.rep.

**Comment by nliu86** [comment]
I checked the files result_K=100.dat and result_K=100.rep. They don't
contain the info I want.

What I need is  a function similar to python function nmslib_vector.
knnQuery(self._index, n, v.tolist())
-----------------------------------------------------

-0-xxx@xxx:~/xxx/result $ cat result_K\=100.dat

MethodName      Recall  Recall@1        PrecisionOfApprox       RelPosError
    NumCloser       ClassAccuracy   QueryTime       DistComp
ImprEfficiency  ImprDistComp Mem      IndexTime       IndexLoadTime
IndexSaveTime   QueryPerSec     IndexParams     QueryTimeParams NumData

"hnsw"  0.9789  1       0.991593        1.00872 0       0       0.44148 0
    82.9783 inf     151     0       0.049498        1e-06   24084.8 ""
"efSearch=100"  145673

-0-xxx@xxx:~/xxx/result $ cat result_K\=100.rep


===================================

hnsw

Index parameters:

Query-time parameters: efSearch=100

===================================

# of points: 145673

# of queries: 100

------------------------------------

Recall:            0.979 -> [0.979 0.979]

Recall@1:          1 -> [1 1]

PrecisionOfApprox: 0.992 -> [0.992 0.992]

ClassAccuracy:     0 -> [0 0]

RelPosError:       1.01 -> [1.01        1.01]

NumCloser:         0 -> [0      0]

------------------------------------

QueryTime:         0.44 -> [0.39        0.49]

QueryPerSec:       24084.8 -> [24084.8  24084.8]

DistComp:          0 -> [-0     0]

------------------------------------

ImprEfficiency:    82.98 -> [82.98      82.98]

ImprDistComp:      inf -> [inf  inf]

------------------------------------

Memory Usage:      151.85 MB

Index Time:        0 sec

------------------------------------

**Comment by searchivarius** [comment]
These are query results, no?

**Comment by nliu86** [comment]
Yes, that's result after I ran the following command:

/Users/naiping_liu/nmslib-1.5.3/similarity_search/release/experiment \
--distType float --spaceType l2 \
--knn 100 \
--dataFile ../head.num.txt --outFilePrefix result \
--queryFile ../head.num.txt_testset \
--method hnsw \
--queryTimeParams efSearch=100 \
--loadIndex hnsw_index \
--logFile logQuery.txt \
--threadTestQty 40

**Comment by searchivarius** [comment]
If you need query timings. This is exactly what you need. If you need IDs you have two choices to retrieve them:
1) Use C++ API directly. The example is here: https://github.com/searchivarius/nmslib/blob/master/sample_standalone_app/sample_standalone_app1.cc
2) You can also use the query server:  https://github.com/searchivarius/nmslib/tree/master/query_server/cpp_client_server
Query server requires Apache Thrift 0.9.2 (see also section 2.5 of the manual).

**Comment by nliu86** [comment]
Yes, I need IDs. I will try the choices below. Thanks a lot!

**Comment by searchivarius** [comment]
No problem. Hope this was helpful.

**Comment by nliu86** [comment]
Yes, this is helpful! I used to use Annoy for my similarity search until
one month ago I found your nmslib which I really like and plan to use as
one of most important piece of packages for my text deep learning efforts.
Is there a mailing list or discussion forum for this lib?

My data set is like 1 million items with each item 100 dimension vector.
There are two very important tasks:

1. For each item in the 1 million items, I need to find 100-NN. Is the
query-server most suitable for this task? Also if I build the index with
method hnsw, does it mean I can retrieve the k-NN very efficiently since we
already know the location for each item?

2. I have additional 10k new items which are not in the original 1 million
items and I need to find 100-NN. Is the query-server still the best way to
do this?

Thanks a lot!

Nick

**Comment by searchivarius** [comment]
Hi,
there's no discussion board yet.
1 million items isn't a lot, especially if you use a reasonable efConstruction (200 is usually more than enough).
The query server is suitable for this task. The advantage of query server is that it's Apache thrift. Therefore, you can call it over TCP/IP from Java and Python (and actually you could probably generate Thrift classes for all Thrift-supported langauages).
However, you can use C++ API directly.
Yes, HNSW is very efficient, just don't copy parameters verbatim from ann-benchmark test. You can probably use smaller M and smaller efConstruction.
Regarding the additional 1 million items: why don't you merge them with the 1M original data set?
PS: there's no list yet. If really a lot of people start using NMSLIB, we would need to setup one.

**Comment by nliu86** [comment]
Thanks for your quick response and advice! I have the feeling that NMSLIB
will become very useful because we need to do similarity search everywhere.
Solr and Lucene are good for text similarity match. I have a way to turn
short text into numerical vectors and then do semantic similarity search
which has much better results.

Right now we're using Annoy in our offline and production system to find
most similar queries for a given query. I plan to replace them with NMSLIB.
There are two kinds of queries: popular queries and unpopular queries.

The number of popular queries is finite, say 1M. For them, we need to find
other popular queries similar to them. After some post processing, we build
a dictionary that maps a given popular query to other popular queries. The
dictionary will be used in live system. It would be great if we can use
batch processing to off-line build the dictionary quickly. Between query
server and C++/Python API, which one is better for batch processing?

The number of unpopular queries is infinite. They come in from live system
one by one. So we cannot merge them with the original 1M popular queries.
For these unpopular queries, the first task is to find most similar popular
queries. We need to do it very fast in live system.

Thanks,

Nick

**Comment by searchivarius** [comment]
Hi Nick,

This is great. Would you mind answering a couple of question by e-mail (leo@boytsov.info)?

**Comment by nliu86** [comment]
sure, I'm happy to.

Nick
