### ISSUE TITLE
Make failed in linking Boost library

### ISSUE THREAD

**Issue by nguyenv7** [searchivarius/nmslib#134]
Hello,

I am facing an error in this step:

> [ 75%] Linking CXX executable ../release/experiment

All of errors liked that: 

> undefined reference to `boost::program_options:

I install latest libraries version and checked that libboost 1.58 is compatible with g++ 4.9. I think maybe it related with C++11, however It returns error in both g++ 4.9 and 4.7.

This is my system information: 

> -- The C compiler identification is GNU 4.9.3
> -- The CXX compiler identification is GNU 4.9.3
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Build type: Release
> -- GSL using gsl-config /usr/bin/gsl-config
> -- Using GSL from /usr
> -- Found GSL.
> -- Found Eigen3: /usr/include/eigen3 (Required is at least version "3") 
> -- Found Eigen3.
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   system
> --   filesystem
> --   program_options
> -- Found BOOST.
> 

I also install Clang and LLDB 3.6. I tried search many possible solution but can not fix that :(.

**Comment by searchivarius** [comment]
Hi,

sorry about that. Did you try to remove CMake cache or build from clean
clone?

If all else fail you can try development branch. We are getting rid of
Boost to eliminate situations like yours.

**Comment by nguyenv7** [comment]
Hello,

I did that before and change version of g++ and gcc to hope it successful. 

> rm -rf `find . -name CMakeFiles` CMakeCache.txt

But still same errors, I will try the dev branch definitely.

Thanks you,

**Comment by searchivarius** [comment]
Interesting,

What kind of OS do you use?

---
Leo

**Comment by nguyenv7** [comment]
Hello,

I am using Ubuntu 16.04

**Comment by searchivarius** [comment]
Try to install boost program options separately:
```
sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev 
```

**Comment by nguyenv7** [comment]
Hello,

I installed it before. I just try to clean and remake the master branch but still fail. 
Here is the libboost installation in my system.

> find /usr/lib -name 'libboost*'
> /usr/lib/x86_64-linux-gnu/libboost_program_options.a
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_timer.a
> /usr/lib/x86_64-linux-gnu/libboost_math_c99.so
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py35.a
> /usr/lib/x86_64-linux-gnu/libboost_coroutine.a
> /usr/lib/x86_64-linux-gnu/libboost_serialization.a
> /usr/lib/x86_64-linux-gnu/libboost_signals.a
> /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1.so
> /usr/lib/x86_64-linux-gnu/libboost_locale.so
> /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_mpi.a
> /usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.a
> /usr/lib/x86_64-linux-gnu/libboost_wave.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_serialization.so
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.so
> /usr/lib/x86_64-linux-gnu/libboost_log_setup.a
> /usr/lib/x86_64-linux-gnu/libboost_signals.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_c99l.so
> /usr/lib/x86_64-linux-gnu/libboost_wserialization.so
> /usr/lib/x86_64-linux-gnu/libboost_coroutine.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_context.so
> /usr/lib/x86_64-linux-gnu/libboost_exception.a
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py35.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_graph_parallel.a
> /usr/lib/x86_64-linux-gnu/libboost_locale.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_date_time.a
> /usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_wserialization.a
> /usr/lib/x86_64-linux-gnu/libboost_math_c99.a
> /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_c99f.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so
> /usr/lib/x86_64-linux-gnu/libboost_atomic.so
> /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
> /usr/lib/x86_64-linux-gnu/libboost_thread.a
> /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a
> /usr/lib/x86_64-linux-gnu/libboost_system.so
> /usr/lib/x86_64-linux-gnu/libboost_system.a
> /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_regex.a
> /usr/lib/x86_64-linux-gnu/libboost_math_c99l.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_filesystem.a
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py35.so
> /usr/lib/x86_64-linux-gnu/libboost_mpi.so
> /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_thread.so
> /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_c99f.a
> /usr/lib/x86_64-linux-gnu/libboost_chrono.a
> /usr/lib/x86_64-linux-gnu/libboost_context.a
> /usr/lib/x86_64-linux-gnu/libboost_log.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_python.so
> /usr/lib/x86_64-linux-gnu/libboost_regex.so
> /usr/lib/x86_64-linux-gnu/libboost_python-py35.a
> /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_test_exec_monitor.a
> /usr/lib/x86_64-linux-gnu/libboost_iostreams.so
> /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.a
> /usr/lib/x86_64-linux-gnu/libboost_math_c99f.so
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1.a
> /usr/lib/x86_64-linux-gnu/libboost_wave.so
> /usr/lib/x86_64-linux-gnu/libboost_chrono.so
> /usr/lib/x86_64-linux-gnu/libboost_log_setup.so
> /usr/lib/x86_64-linux-gnu/libboost_program_options.so
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python.a
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so
> /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_python-py27.a
> /usr/lib/x86_64-linux-gnu/libboost_log_setup.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_graph.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_context.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_date_time.so
> /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so
> /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_c99l.a
> /usr/lib/x86_64-linux-gnu/libboost_iostreams.a
> /usr/lib/x86_64-linux-gnu/libboost_coroutine.so
> /usr/lib/x86_64-linux-gnu/libboost_atomic.a
> /usr/lib/x86_64-linux-gnu/libboost_log.a
> /usr/lib/x86_64-linux-gnu/libboost_wave.a
> /usr/lib/x86_64-linux-gnu/libboost_timer.so
> /usr/lib/x86_64-linux-gnu/libboost_wserialization.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1f.a
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1l.a
> /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
> /usr/lib/x86_64-linux-gnu/libboost_signals.so
> /usr/lib/x86_64-linux-gnu/libboost_random.so
> /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so
> /usr/lib/x86_64-linux-gnu/libboost_graph.so
> /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
> /usr/lib/x86_64-linux-gnu/libboost_timer.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so
> /usr/lib/x86_64-linux-gnu/libboost_log.so
> /usr/lib/x86_64-linux-gnu/libboost_math_c99.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_graph.a
> /usr/lib/x86_64-linux-gnu/libboost_random.so.1.58.0
> /usr/lib/x86_64-linux-gnu/libboost_locale.a
> /usr/lib/x86_64-linux-gnu/libboost_mpi_python.so
> /usr/lib/x86_64-linux-gnu/libboost_python.a
> /usr/lib/x86_64-linux-gnu/libboost_random.a
> /usr/lib/i386-linux-gnu/libboost_system.so.1.58.0
> /usr/lib/i386-linux-gnu/libboost_filesystem.so.1.58.0

I found that all of the error are came from 

>  undefined reference to `boost::program_options::error

I search that article is very helpful, but I can not modify anything:
http://stackoverflow.com/questions/8454329/why-cant-clang-with-libc-in-c0x-mode-link-this-boostprogram-options-examp

**Comment by searchivarius** [comment]
This makes sense, thank you. One more stimuls to get rid of boost as soon as possible :-)
However, I am a bit confused. Above you write that you use GCC not CLANG. With CLANG you can't use HNSW (it's not working with CLANG yet).

**Comment by nguyenv7** [comment]
Actually I used GCC, I installed Clang but not use. I also redefine the environment as

> export CCX=g++-4.7 CC=gcc-4.7

So what I can do now ? What specific version of your Gcc and libboost that are successful in install Nmslib ? 

I am managing to use this library to add some binary distances for binary data.

**Comment by searchivarius** [comment]
I just noticed that your find command to delete cache doesn't seem to be correct:
```
find . -name CMakeFiles CMakeCache.txt
```
The issue that you linked above is only for Clang. It works with boost and Ubuntu 16 for me with g++-4.8.

So, may be your cmake version is much different, but I doubt. I use
```
cmake version 3.5.1
```

**Comment by searchivarius** [comment]
PS: I suspect that you didn't delete CMake cache.

**Comment by nguyenv7** [comment]
Hello,

I remove Clang and CMake cache, also make clean, my cmake version is 3.5.1. Of course, it rebuild from the beginning and same errors:

```
 76%] Linking CXX executable ../release/experiment
../release/libNonMetricSpaceLib.a(params_cmdline.cc.o): In function `similarity::ParseCommandLine(int, char**, bool&, std::string&, std::string&, std::string&, std::string&, std::string&, std::shared_ptr<similarity::AnyParams>&, unsigned int&, bool&, std::string&, unsigned int&, std::string&, std::string&, std::string&, float&, unsigned int&, unsigned int&, std::vector<unsigned int, std::allocator<unsigned int> >&, float&, std::string&, std::string&, std::shared_ptr<similarity::AnyParams>&, std::vector<std::shared_ptr<similarity::AnyParams>, std::allocator<std::shared_ptr<similarity::AnyParams> > >&)':
params_cmdline.cc:(.text+0x3ad): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'

```

**Comment by searchivarius** [comment]
Are you sure? What's the exact cleaning command line. The command that you cited above doesn't work. To reiterate, this one **is wrong**:
```
rm -rf find . -name CMakeFiles CMakeCache.txt
```

**Comment by nguyenv7** [comment]
Hello,

I removed all Cmake related files by hand in the last comment. This time I delete the nmslib folder and extract the archive file again, but the same error.
Thanks you for notification, the cmake cleaning command I copied in the manual does not work; I also recheck this, the find command syntax is not right. 

I am sorry that maybe cost your time, but I honestly try many ways until now to get it work.

**Comment by searchivarius** [comment]
Hi, ok, thank you for confirming.

Regarding the command in the manual: you seem to have lost two '`'.

I will try to reproduce this bug in a virtual machine (Ubuntu 16). Can't reproduce on my own machine which also uses Ubuntu 16, but this is not a clean install. 

In any case, please, try the dev bracnh. Relatively soon, we will remove boost from the main build, so it won't be a pain (it is also a pain on Windows).

**Comment by nguyenv7** [comment]
Thanks you,

Actually, my Ubuntu system is not so clean too, but related things are in the right place. Hope you can find the reason. I am trying the dev branch now.

**Comment by bileg** [comment]
It seems like that the linker can't find boost libraries (i.e. program options lib). So could you compile the code again:
     cmake .
     make VERBOSE=1
Then you should see -lboost_program_options-mt (or without -mt) in the linker command being run by cmake.

**Comment by nguyenv7** [comment]
Hello,

Thanks you for the suggestion. Here is the linker command for boost:

`-lboost_filesystem -lboost_program_options -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm -lpthread`

**Comment by bileg** [comment]
OK.
Could you check the following code if it works for you:

[bileg@similarity_search]$ cat popt.cc
#include <iostream>
#include <boost/program_options.hpp>
namespace po = boost::program_options;
int main() {
  po::options_description cmd_opt("test");
  std::cout << "ok\n";
}
[bileg@similarity_search]$ g++ popt.cc 
/tmp/cclO7B78.o: In function `main':
popt.cc:(.text+0xd): undefined reference to `boost::program_options::options_description::m_default_line_length'
popt.cc:(.text+0x18): undefined reference to `boost::program_options::options_description::m_default_line_length'
popt.cc:(.text+0x51): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
[bileg@similarity_search]$ g++ popt.cc -L/usr/local/lib -lboost_system-mt -lboost_program_options-mt              # (i think you can use:   g++ popt.cc -lboost_system -lboost_program_options -L/usr/lib/x86_64-linux-gnu)
[bileg@similarity_search]$ ./a.out
ok

**Comment by searchivarius** [comment]
I can actually reproduce this bug for the clean Ubuntu 16 install. I will try to @bileg's code

**Comment by nguyenv7** [comment]
I try to run @bileg code, the same problem in linking stage:

```
g++ popt.cc -lboost_system -lboost_program_options -L/usr/lib/x86_64-linux-gnu
/tmp/ccXNGnl7.o: In function `main':
popt.cc:(.text+0x6c): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status

```

**Comment by bileg** [comment]
OK. It means that /usr/lib/x86_64-linux-gnu doesn't contain required boost libraries. So you can do:
find /usr -name *boost*.so
If you find a directory that contains libboost_program_options.so then you need to add -L/usr/.... (the directory you just found)
If it doesn't work you could try another option:
https://github.com/searchivarius/nmslib/blob/master/similarity_search/CMakeLists.txt#L122
But you have to download and compile boost and then link.

**Comment by bileg** [comment]
somehow asterisk disappeared from the command it should be `find /usr -name *boost*.so`

**Comment by nguyenv7** [comment]
Hello, 

I checked that library's location before in this comment:
https://github.com/searchivarius/nmslib/issues/134#issuecomment-254496558

Is it ok ?

**Comment by bileg** [comment]
Sorry, I overlooked that then everything should be fine. Could you try the second approach that I suggested (CMakeLists.txt#L122)

**Comment by nguyenv7** [comment]
Thanks you,

Wait me a little bit, I will download and make a hardwired link to boost then.

**Comment by nguyenv7** [comment]
Thanks @bileg and @searchivarius , after compiling and linking in CMakeLists.txt#L122. The library was built successfully.
