### ISSUE TITLE
Possible to delete data after index creation?

### ISSUE THREAD

**Issue by bkj** [searchivarius/nmslib#135]
I was wondering whether it's possible to delete the actual data after the index is created, as a potential way to save memory footprint.  I'm not super familiar with the underlying algorithms, so apologies if the data already gets deleted or this is an otherwise silly question.  

Thanks

**Comment by searchivarius** [comment]
Hi, data is needed.

PS: We should really think about implementing more memory efficient variants :-)

**Comment by bkj** [comment]
Ah alright  Yes I agree about more memory efficient variants -- something similar to Annoy's `mmap` functionality would be really wonderful. Thanks for the quick reply!

**Comment by searchivarius** [comment]
Yeah, I am actually thinking about mmap-ing data. This will be useful: https://github.com/searchivarius/nmslib/issues/133
