### ISSUE TITLE
vectorized operation in Python

### ISSUE THREAD

**Issue by alekk** [searchivarius/nmslib#138]
First, many thanks for all the great work! This is extremely useful to the community.

When using the Python wrapper, I am wondering whether there is a way to avoid adding samples one by one through the function "nmslib_vector.addDataPoint" and querying samples by samples through the function "nmslib_vector.knnQuery". Loops are just too slow in Python!

Cheers!

**Comment by bileg** [comment]
I think it's possible to support that. For vectors, probably it's better to use numpy arrays instead of python's lists. I can have a look at it.

**Comment by alekk** [comment]
Numpy array support would be fantastic, indeed!

**Comment by searchivarius** [comment]
Hi @alekk after some discussion with @bileg we concluded that having a shared array is not such an easy thing to implement, b/c we store additional metadata with data. Sometimes, this is not necessary and sometiems it is. To remake the library so that it can switch between this alternatives depending on the space that we use, will not be easy.

**Comment by alekk** [comment]
I see, thanks.

And how difficult would it be to have a routine that can quickly compute k-nearest neighbors, as done by the function "kneighbors_graph" of scikit-learn.

http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.kneighbors_graph.html

**Comment by searchivarius** [comment]
We currently have no plans to support such a function, but contributions are welcome.

Regarding your original question: one work around that other people were using is to call addDataPoint in a multi-threaded mode. **This still requires some updates to Python API**, but I am going to release them soon.

Also: would it be helpful if you have a function addDataPoints, which accepts an array or list? Then, data points could be added in large batches (still without loading everything to memory).

**Comment by alekk** [comment]
Thanks @searchivarius , that would indeed be very helpful to have such an array/list version of addDataPoints.

In my particular application, loading everything in memory is not the bottleneck. I must admit that I still do not perfectly understand why it is easier to have an array version for "addDataPoints" but not for "knnQuery"?

**Comment by searchivarius** [comment]
It's not just keeping, it would keeping things twice. 

I didn't get what do you mean by an array version of knnQuery?

**Comment by alekk** [comment]
by array version of knnQuery, I meant a version where I could do 

> knnQuery(index, k, array_of_data)

instead of looping over "array_of_samples" and call  knnQuery(index, k,data) for each "data" in "array_of_data". This would output an array of dimension: (length of array_of_data) x k. Is it already doable in the current implementation, I am not sure?

**Comment by searchivarius** [comment]
@alekk yes, it is doable. Moreover, it can be automatically thread-pooled. Well, this would be a time saving for sure. You are welcome to create a separate issue-feature request (or implement this code yourself and submit a pull request :-).

However, the major problem is that adding data points is slow adn there's no good work around except making it multi-threaded. 

So, to sum up this thread: we seem to agree that adding data points in big batches will solve the problem, right?

**Comment by bileg** [comment]
@alekk could you check the following version in my repo if it works faster: https://github.com/bileg/nmslib/blob/bulk_index/python_vect_bindings/test_nmslib_vect.py#L29
https://github.com/bileg/nmslib/blob/bulk_index/python_vect_bindings/test_nmslib_vect.py#L96
https://github.com/bileg/nmslib/blob/bulk_index/python_vect_bindings/test_nmslib_vect.py#L129

**Comment by bileg** [comment]
I did a bit refactoring so the line numbers that I previously mentioned are changed. Anyway the branch is https://github.com/bileg/nmslib/blob/bulk_index/python_vect_bindings (hope that it supports fast batch insertion and search)

**Comment by searchivarius** [comment]
Thanks to @bileg we have it in the develop version. @alekk would you care to try, thanks!
I am closing this issue.
