### ISSUE TITLE
nmslib support for external id

### ISSUE THREAD

**Issue by zjxheng** [searchivarius/nmslib#140]
hi, 
I'm using nmslib, now I found hnsw can't support space "-s word_embed:dist=cosine" when  i want to save the index "-S test.index".   The err msg is below

2016-11-08 00:09:11 QueryService_server.cpp:130 (QueryServiceHandler) [INFO] Saving the index
terminate called after throwing an instance of 'std::runtime_error'
  what():  Storing non-optimized index is not supported yet!

Is't a bug?  Best wishes!

**Comment by searchivarius** [comment]
No, unfortunately, this is indeed not supported yet, sorry.

**Comment by zjxheng** [comment]
Thanks!  Now I find method hnsw support it , I will use sw-graph instead of hnsw.

**Comment by searchivarius** [comment]
Yes, we do plan to support it. Sorry, a lot of stuff is in the experimental state now, but we are working towards making it more robust.
