### ISSUE TITLE
hnsw/sw-graph  support    Increment recoder??

### ISSUE THREAD

**Issue by zjxheng** [searchivarius/nmslib#142]
hi， 

I want insert increment recoder into hnsw/sw-graph.  Do they support??

**Comment by searchivarius** [comment]
Do you mean updating existing embedding and re-indexing them?

**Comment by zjxheng** [comment]
oh,  sorry, i did't express clearly. 
Dose the nmslib support updating/adding/delete like a database when it's providing the searching service?

**Comment by searchivarius** [comment]
Not yet, but we plan to support updates. Do you need deletion as well as update?

**Comment by zjxheng** [comment]
Maybe  update can replace deletion.   Dose the nmslib supports  adding?

**Comment by searchivarius** [comment]
Not yet.
