### ISSUE TITLE
How to set parameter searchMethod in hnsw?

### ISSUE THREAD

**Issue by nliu86** [searchivarius/nmslib#143]
When loading index, I noticed the following even though I didn't set this parameter
016-11-08 23:22:53 hnsw.cc:746 (LoadIndex) [INFO] searchMethod: 3

In the manual for hnsw, searchMethod is set to be 4
--createIndex M=10,efConstruction=20,indexThreadQty=4,searchMethod=4 \

Is this parameter similar to post parameter? How to set it?

**Comment by searchivarius** [comment]
It is set automatically.
