### ISSUE TITLE
Any way to silence the logger?

### ISSUE THREAD

**Issue by cjamin** [searchivarius/nmslib#148]
Hi,
I had a look at the code in `logging.h`, but it seems there is no way to silence the LOG macro. Am I right?
Thanks!

**Comment by searchivarius** [comment]
No, you can silence logging/printing in 2 places:
1) When you call init_library
2) When you call createMethod, you can specify printProgress = false.
If you have further generic questions, please, use a newly created gitter forum https://gitter.im/nmslib/Lobby
Thank you!

**Comment by cjamin** [comment]
Thanks. I had already set printProgress = false, but it was not enough.
initLibrary did the trick!
