### ISSUE TITLE
advice on choosing a proper method

### ISSUE THREAD

**Issue by AdrianYu** [searchivarius/nmslib#151]
Say that I have half a million data points, each point is a sparse vector of length 1500. The average number of non-zero elements per sample is about 100 or more. I mainly care about querying speed. Index building procedure also need to be done around 10 minute or so. A recall accuracy of 80% should be enough. Given these requirements, which method should I choose? Or is it possible using nmslib?

**Comment by searchivarius** [comment]
Hi @AdrianYu, let's move this discussion to https://gitter.im/nmslib/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
thanks!
