### ISSUE TITLE
Hnsw saves and loads options in index file by wrong byte-size

### ISSUE THREAD

**Issue by kinoyasu** [searchivarius/nmslib#152]
Hnsw::SaveIndex() and Hnsw::LoadIndex() write and read

maxlevel_
enterpointId_
totalElementsStored_
dist_func_type_

by "sizeof(size_t)"
(similarity_search/src/method/hnsw.cc)

But them are defined as "int" or "unsigned int".
(similarity_search/include/method/hnsw.h)

In 64bit environment, they are different size in bytes, should be same size for safe.

**Comment by searchivarius** [comment]
Hi @kinoyasu 

which system do you have. I believe that unsigned int should be normally the same size as int. E.g., try this program:
```
#include <cmath>
#include <iostream>

using namespace std;
int main() {
  cout << sizeof(unsigned int) << endl;
  cout << sizeof(int) << endl;
}
```

**Comment by searchivarius** [comment]
@kinoyasu sorry, disregard my previous answer, I misread your report. Thank you for pointing this out, yeah, this seems like a problem.

**Comment by kinoyasu** [comment]
@searchivarius Thank you. My comment was not accurate. The problem is mainly at 64bit GCC (int:32bits ; size_t:64bits ).  int at 64bit VisualStudio is 64bits.
The unsafe is that the read size might be larger than their memory allocation.
If their allocations are aligned with 32bit for saving memory, should cause overflow.

**Comment by searchivarius** [comment]
@kinoyasu your comment is fine, fix is underway, thanks!

**Comment by searchivarius** [comment]
I believe it should be fine now in *develop*. I will soon propagate these changes to other branches.
