### ISSUE TITLE
Can't compile on Arch Linux

### ISSUE THREAD

**Issue by davidanastasiu** [searchivarius/nmslib#161]
I get a compile error using either GCC 6.2.1 or GCC 5.4.1. It starts with:
In file included from /usr/include/c++/6.2.1/random:50:0,
                 from /home/dragos/programs/nmslib/similarity_search/include/utils.h:33,
                 from /home/dragos/programs/nmslib/similarity_search/src/distcomp_bregman.cc:18:
/usr/include/c++/6.2.1/x86_64-pc-linux-gnu/bits/opt_random.h: In member function ‘void std::normal_distribution<_RealType>::__generate(std::normal_distribution<_RealType>::result_type*, std::normal_distribution<_RealType>::result_type*, _UniformRandomNumberGenerator&, const std::normal_distribution<_RealType>::param_type&) [with _UniformRandomNumberGenerator = _UniformRandomNumberGenerator; _RealType = double]’:
/usr/include/c++/6.2.1/x86_64-pc-linux-gnu/bits/opt_random.h:70:15: error: ‘__m128i’ does not name a type
  static const __m128i __mask = _mm_set1_epi64x(__maskval);
               ^~~~~~~
/usr/include/c++/6.2.1/x86_64-pc-linux-gnu/bits/opt_random.h:71:15: error: ‘__m128i’ does not name a type
  static const __m128i __two = _mm_set1_epi64x(0x4000000000000000ull);
               ^~~~~~~
/usr/include/c++/6.2.1/x86_64-pc-linux-gnu/bits/opt_random.h:72:15: error: ‘__m128d’ does not name a type
  static const __m128d __three = _mm_set1_pd(3.0);
               ^~~~~~~
/usr/include/c++/6.2.1/x86_64-pc-linux-gnu/bits/opt_random.h:73:8: error: ‘__m128d’ does not name a type
  const __m128d __av = _mm_set1_pd(__param.mean());
        ^~~~~~~
/usr/include/c++/6.2.1/x86_64-pc-linux-gnu/bits/opt_random.h:83:6: error: ‘__m128d’ was not declared in this scope
      __m128d __x;
      ^~~~~~~
...

It seems to have something to do with the SSE code. Any ides how I could get this to compile?

Thanks,
David

**Comment by searchivarius** [comment]
@davidanastasiu which version of archlinux? interestingly, it doesn't seem to complain about our SSE, it complains about ``/usr/include/c++/6.2.1/x86_64-pc-linux-gnu/bits/opt_random.h``

**Comment by davidanastasiu** [comment]
I'm running Kernel linux 4.8.13-1.

**Comment by searchivarius** [comment]
Please, try an updated source from the master branch.

**Comment by davidanastasiu** [comment]
It worked. What was the issue?

**Comment by searchivarius** [comment]
Thanks a lot for checking!

Due to lack of foresought, intrinsic headers were included **within our namespace**, which effectively excluded them from global workspace. The archlinux platform apparently uses an optimized version of the standard library that relies on intrinsics quite a bit. But we removed these intrinsics from the global space. So, the error message was very weird as if the platform is broken.

**Comment by davidanastasiu** [comment]
That makes sense. Thanks for the explanation!

**Comment by lesteve** [comment]
FYI, I got the same error on Ubuntu 16.10 when trying to compile 1.6. Using master fixed it.

**Comment by searchivarius** [comment]
@lesteve this is quite possible, b/c the fix wasn't included.
