### ISSUE TITLE
Memory leak in small_world_rand and space_sparse_vector_inter.cc

### ISSUE THREAD

**Issue by AdrianYu** [searchivarius/nmslib#165]
In `src/method/small_world_rand.cc` line 727, a `MSWNode` is created for each line, and put in `ElList_`. But in deconstructor, pointers in `ElList_` are not deleted. In `src/space/space_sparse_vector_inter.cc` line 60, a new `Object` is returned, leaving the char array `pData` un-deleted.

**Comment by searchivarius** [comment]
I will look into these, thanks a lot for checking!

**Comment by searchivarius** [comment]
Hi @AdrianYu thanks again for reporting this. Sorry it took me a while, but I believe that the master branch should be fine now.
