### ISSUE TITLE
HNSW Parameters for SIFT Matching

### ISSUE THREAD

**Issue by saedrna** [searchivarius/nmslib#166]
Hi,

Thanks for this wonderful lib. And after check the benchmark results, I would like to change from [FLANN](https://github.com/mariusmuja/flann) (or [FASTANN](https://github.com/philbinj/fastann)) to this lib for SIFT descriptor matching. My sift descriptor is quantized as uint8_t for each element. And I am using HNSW as the index, because it has the best performance in the [benchmark](https://github.com/erikbern/ann-benchmarks).

I have encountered two problems for this.

First, I have successfully export symbols for all the required classes/functions for uint8_t and linked into my program, but if the index and other stuffs are created with uint8_t as dist_t, the matching result is totally wrong. However, which is correct for int. So my first question, is that is it true that we can't use uint8_t as the distance type?

Second, the search time is slower than flann and fastann.  I believe this is from the problem of parameter setting, because I just use the default one and the search precision is almost the same as brute force search in opencv. So my second question is, how to tune the parameter of HNSW for faster computation with reasnable loss of accuracy?

Thanks,

Han

Below is my function doing descriptor search using nmslib.
```

using namespace similarity;
/*
* Define an implementation of the distance function.
*/
template <typename T>
struct DistL2 {
    /*
    * Important: the function is const and arguments are const as well!!!
    */
    float operator()(const T *x, const T *y, size_t qty) const {
        float res = 0;
        typedef Eigen::Matrix<T, Eigen::Dynamic, 1 > VectorXT;
        VectorXT a = Eigen::Map<VectorXT>((T *)x, qty);
        VectorXT b = Eigen::Map<VectorXT>((T *)y, qty);
        return (a.cast<int>() - b.cast<int>()).squaredNorm();
    }
};

void match_nmslib(const cv::Mat &desc1, const cv::Mat &desc2,
                  const vector<cv::KeyPoint> &kpts1, const vector<cv::KeyPoint> &kpts2,
                  vector<cv::KeyPoint> &matched1, vector<cv::KeyPoint> &matched2) {
    ObjectVector    data1, data2;
    const Object   *queryObj = NULL;
    typedef int Real;
    // Create an instance of our custom space that uses L2-distance
    VectorSpaceGen<Real, DistL2<Real>>   customSpace;
    vector<string>                  vExternIds;

    vector<vector<Real>> raw1(desc1.rows), raw2(desc2.rows);
    for (int i = 0; i < desc1.rows; ++i) {
        vector<Real> row_data(desc1.cols);
        for (int j = 0; j < desc1.cols; ++j) {
            row_data[j] = desc1.at<uint8_t>(i, j);
        }
        raw1[i] = row_data;
    }
    for (int i = 0; i < desc2.rows; ++i) {
        vector<Real> row_data(desc2.cols);
        for (int j = 0; j < desc2.cols; ++j) {
            row_data[j] = desc2.at<uint8_t>(i, j);
        }
        raw2[i] = row_data;
    }
    AnyParams IndexParams;
    AnyParams QueryTimeParams;

    customSpace.CreateDataset(data1, raw1);
    customSpace.CreateDataset(data2, raw2);
    initLibrary(LIB_LOGNONE, NULL);


    Index<Real>   *index =
        MethodFactoryRegistry<Real>::Instance().
        CreateMethod(false /* print progress */,
                     "hnsw",
                     "custom",
                     customSpace,
                     data2);
    index->CreateIndex(IndexParams);
    index->SetQueryTimeParams(QueryTimeParams);
    int K = 2;
    auto time1 = std::chrono::system_clock::now();

    float nn_ratio_threshold = 0.85f;
    for (int i = 0; i < desc1.rows; ++i) {
        queryObj = data1[i];
        KNNQuery<Real> knnQ(customSpace, queryObj, K);
        index->Search(&knnQ);

        auto result = knnQ.Result()->Clone();

        auto dist2 = result->TopDistance();
        auto idx2 = result->TopObject()->id();
        result->Pop();
        auto dist1 = result->TopDistance();
        auto idx1 = result->TopObject()->id();

        if (dist1 < nn_ratio_threshold * dist2) {
            matched1.push_back(kpts1[i]);
            matched2.push_back(kpts2[idx1]);
        }
    }

    auto time2 = std::chrono::system_clock::now();
    cout << "time is " << std::chrono::duration_cast<std::chrono::milliseconds>(time2 - time1).count() << endl;

    delete index;
}
```

**Comment by searchivarius** [comment]
Hi, 
1) There is a confusion between data structure and the distance **value** type. Your distance value should still be float. Again, what sort of data you have (it can be uint8_t* or it can be a string) is basically unrelated to the distance type.
2) Before using your custom space, I would recommend playing with the ``experiment`` binary and try to figure out parameter values. The tuning guideline in the manual section 6.2
3) Again, because you use a **custom** space you, unfortunately, cannot use all the power of HNSW. You cannot save indices and you have to set skip_optimized_index to 1. If you need to save indices, you have to use small_world_rand_instead. Methods parameters are described in the manual as well except for the parameter post https://github.com/searchivarius/nmslib/issues/121
4) Last, is your data set large?
