### ISSUE TITLE
Possible memory leak in sample_standalone_app/sample_standalone_app1.cc?

### ISSUE THREAD

**Issue by shubaoliu** [searchivarius/nmslib#173]
In sample_standalone_app/sample_standalone_app1.cc
```
void printResults(KNNQuery<float>* qobj) {
  KNNQueue<float>* res = qobj->Result()->Clone();

  while (!res->Empty()) {
    cout << res->TopObject()->id() << " : " << res->TopDistance() << endl;
    res->Pop();
  }
}
```
Should we add 
`delete res;`
at the end of the function to avoid memory leak?

**Comment by searchivarius** [comment]
Good catch, you are absolutely correct. I have commited changes in master. In fact, we are more careful in Python bindings...
