### ISSUE TITLE
python building failed on non-extended version (Linux)

### ISSUE THREAD

**Issue by lancifollia** [searchivarius/nmslib#183]
The following command will be failed because `liblshkit.a` is not built on non-extra (without `-DWITH_EXTRAS=1`) version.

```
# at similarity search directory
cmake .
make  

# go to python binding directory
python setup.py build
```

This issue can be fixed by adding statements at [setup.py](https://github.com/searchivarius/nmslib/blob/master/python_bindings/setup.py#L10).

```python
import os
    ...
    extra_objects=['%s/libNonMetricSpaceLib.a' % release]
    if os.path.isfile('%s/liblshkit.a' % release):
        extra_objects.append('%s/liblshkit.a' % release)
    ...
```

**Comment by searchivarius** [comment]
thanks!

**Comment by searchivarius** [comment]
@lancifollia  I have update setup.py, please, test an updated version. @bileg could you double check that you can still build bindings on MAC OS?

**Comment by lancifollia** [comment]
@searchivarius I have tested setup.py. no problem

**Comment by searchivarius** [comment]
thank you @lancifollia , on Linux, Mac, or both? :-)

**Comment by bileg** [comment]
@searchivarius it works on MAC.

**Comment by searchivarius** [comment]
@bileg cool, thanks!

**Comment by lancifollia** [comment]
@searchivarius on Linux
