### ISSUE TITLE
HNSW - Negative model size (caused by integer overflow)

### ISSUE THREAD

**Issue by lancifollia** [searchivarius/nmslib#184]
Since [model size is calculated by integer variable](https://github.com/searchivarius/nmslib/blob/master/similarity_search/src/method/hnsw.cc#L358), if a model size is greater than 2GB(=2^31, for 4byte signed integer) a wrong model size(this can be a negative number) will be printed [at here](https://github.com/searchivarius/nmslib/blob/master/similarity_search/src/method/hnsw.cc#L412).

How about using `long long`?

**Comment by searchivarius** [comment]
I will look into this soon, thank you for reporting!

**Comment by searchivarius** [comment]
Should be fixed now, please, check (in the master).
