### ISSUE TITLE
Solving OS X compilation issue

### ISSUE THREAD

**Issue by rperrot** [searchivarius/nmslib#189]
Hi,

I wanted to test the library on OS X using standard apple compiler. Using the develop branch, it fails to compile (I only tested similarity_search directory for now). 

The issue is the following : 

> use of undeclared identifier '_MM_HINT_T0'

The _mm_prefect is an SSE instruction so you may include xmmintrin.h instead of mmintrin.h (which is MMX only). If I replace the include of mmintrin.h by xmmintrin.h in the following files :

> src/method/hnsw.cc
> src/method/pivot_neighb_invindx.cc 
> src/method/small_world_rand.cc 
> src/method/vptree.cc 

now the library compiles fine using the standard apple compiler. I also tested using macports version of clang (4.0) and it works too. 

I don't know the implications on the rest of the library and on the other platforms (that's why I didn't make a PR) but it may be a simple approach to solve compilation issue on OS X.

**Comment by searchivarius** [comment]
Hi @rperrot thank you for the issue, this problems seems to be solved in the master branch: https://github.com/searchivarius/nmslib/issues/105 but it is certainly present in some versions. Which branch/release do you use?

**Comment by rperrot** [comment]
I only tried the develop branch.

**Comment by searchivarius** [comment]
@rperrot ohh, I see let me merge master into develop.

**Comment by searchivarius** [comment]
@rperrot please, try to pull from the develop and recompile (please, do cmake . first and may be even remove cmake caches).

**Comment by rperrot** [comment]
That's ok in develop branch now. (either with standard apple compiler and macports clang-4.0). Thanks for your support. 

Finally, jjust a question to understand your development process : what is the most stable branch ? master or develop ?

**Comment by searchivarius** [comment]
@rperrot thank you for checking. master is a bit more stable, but the library is being actively developed.
