### ISSUE TITLE
How can I use the lib in my own code?

### ISSUE THREAD

**Issue by yaomingshr** [searchivarius/nmslib#193]
Hi, I want to use the lib in my own code to do some similar search. But in the manual I don't find any demo or API instructions. I want to do this in C++. Did I miss something? How can I user the lib in my own code?

**Comment by searchivarius** [comment]
Hi, I just a similar question on gitter: https://gitter.im/nmslib/Lobby?at=591a5f8c8a05641b11876827

I should update the manual/README to make it easier to find these examples.

Thanks!

**Comment by yaomingshr** [comment]
Here is what i want to do: In a offline task, create index with whole dataset and persist index into local file. In a online server, read index local file and offer query service.

Can I do this throw our lib now? If I can, is there any demo for me?

Thanks a lot!

**Comment by searchivarius** [comment]
There are demos if you follow the above link. NMSLIB also has its own simple query server: So, there are demos to call the server as well: https://github.com/searchivarius/nmslib/tree/master/query_server
