### ISSUE TITLE
Memory leak in Python (again)

### ISSUE THREAD

**Issue by ducha-aiki** [searchivarius/nmslib#199]
Very similar to the old problem in https://github.com/searchivarius/nmslib/issues/137 
Snippet to reproduce:

     import nmslib
     import numpy.random as npr
     import resource
     import numpy as np
     for i in range(10):
        index = nmslib.init('cosinesimil', [], 'hnsw',
    		                   nmslib.DataType.DENSE_VECTOR,
		                   nmslib.DistType.FLOAT)
        dataset = [map(float, vect) for vect in npr.randn(1000, 8)]
        query =npr.randn(100, 8).astype(np.float32)
        for id, item in enumerate(dataset):
	    nmslib.addDataPoint(index, id, item)
        nmslib.createIndex(index, [])
        nmslib.setQueryTimeParams(index, [])
        for idx in xrange(1000):
           nn = nmslib.knnQueryBatch(index, 4, 1,query)
        nmslib.freeIndex(index)
        print resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

**Comment by searchivarius** [comment]
Hi @ducha-aiki thank you for noticing this. It seems to be a different issue.

**Comment by searchivarius** [comment]
Hi @ducha-aiki , I think this is now fixed by PR #262 
Note that with a new API calling freeIndex is not necessary. @benfred created this dummy method for backward compatibility. Memory will be claimed by a Python garbage collector. So for your benchmark you may want to call gc.collect() to see result. Here is a sample script (please, note that your way to create a data set array fails with Python3):
```
import nmslib
import numpy.random as npr
import resource
import numpy as np
import gc


for i in range(100):
  index = nmslib.init('cosinesimil', [], 'hnsw',
                     nmslib.DataType.DENSE_VECTOR,
                     nmslib.DistType.FLOAT)
  dataset = npr.randn(20000, 8)
  query =npr.randn(100, 8).astype(np.float32)
  for itId, item in enumerate(dataset):
    nmslib.addDataPoint(index, itId, item)
  nmslib.createIndex(index, [])
  nmslib.setQueryTimeParams(index, [])
  for idx in range(2000):
    nn = nmslib.knnQueryBatch(index, 4, 1,query)
  #nmslib.freeIndex(index)
  print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
  gc.collect()

print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
gc.collect()
pr
```
Thanks!

**Comment by chapleau** [comment]
Hi,
just wondering if this fix will be available in a new version to be published on pypi soon (i.e. a matter of days) ? Or are we better off cloning and compiling develop for now ?
Thanks !

**Comment by searchivarius** [comment]
@chapleau I can push it to pypy in a matter of days if you it's convenient (b/c all major fixes are done), but I won't be able to test the Windows and other OSes builds properly. Docs will also take a bit longer to update.
thanks!

**Comment by chapleau** [comment]
Running Linux here so that'd be perfect. Thanks for the prompt response!

**Comment by chapleau** [comment]
Hi @searchivarius , in the meantime would you recommend fetching the latest develop branch or is there a slightly older commit that'd be closer to future version 1.7 ?

**Comment by searchivarius** [comment]
@chapleau sorry about the delay. I think the latest thing is ready, I am only working on integration tests.

**Comment by searchivarius** [comment]
@chapleau we do have it now in pypi repository.
