### ISSUE TITLE
A bug in small_world_rand.cc

### ISSUE THREAD

**Issue by xreborner** [searchivarius/nmslib#213]
The line 831:
  ElList_.insert(make_pair(node->getData()->id(), node.release()));

The evaluation order of "node->getData()->id()" and "node.release()" is implementation-dependent. In my gcc environment, the right part is evaluated first, causing a null dereference in the left part.

Furthermore, I found that pEntryPoint_ is not initialized in LoadIndex(), so knn-query failed after loading index. Could you fix that? Thank you.

**Comment by searchivarius** [comment]
Hi @xreborner you are right about UB, I will look into this issue as well as into the issue with pEntryPoint_ ASAP. Thank you for reporting!

**Comment by searchivarius** [comment]
Hi @xreborner thanks again for reporting this. I believe that the master branch should be fine now. Sorry it took me a while.
