### ISSUE TITLE
About distance ‘nan’ in the result

### ISSUE THREAD

**Issue by mrcsunshine** [searchivarius/nmslib#217]
HI,
  I'm using 2000 dimension vector to construct index with HNSW. But when searching with knnQuery ,the searching results in distances are like this [nan,nan,nan,nan] . I changed different params for building and query time, but it still not work. Can someone help me with that?

**Comment by searchivarius** [comment]
Hi @mrcsunshine ,
it's hard to tell without details:
1) What's the data
2) What's the distance
3) Which parameters do you use. Ideally a code snippet is needed.

**Comment by searchivarius** [comment]
I have to close this, b/c there's no data for reproducing this bug.
