### ISSUE TITLE
Python binding inquiry

### ISSUE THREAD

**Issue by bluejay9676** [searchivarius/nmslib#223]
```python
space_type = 'l2_sparse'
    space_param = []
    method_name = 'lsh_gaussian'
    index_name  = method_name + '_sparse.index'
    if os.path.isfile(index_name):
        os.remove(index_name)
    index = nmslib.init(space_type,
                        space_param,
                        method_name,
                        nmslib.DataType.SPARSE_VECTOR,
                        nmslib.DistType.FLOAT)

```

would throw 
```
RuntimeError: 2017-08-06 14:19:00 methodfactory.h:61 (CreateMethod) It looks like the method lsh_gaussian is not defined for the distance type : FLOAT
```

same goes for when I used DOUBLE. What can I do to get through this? Thank you!

**Comment by bluejay9676** [comment]
Same thing happens when I use other sparse spacetype.

**Comment by searchivarius** [comment]
LSH is only for evaluation purposes. In fact, we have to copy all the data to make it possible. In that, the only sparse LSH is a FALCONN port. However, HNSW is clearly a better choice. Also, if you have non-negative sparse vectors, NAPP (sometimes with **generated pivots**) can work better in some cases. It will also create an index faster.
