### ISSUE TITLE
Documentation for python wrapper

### ISSUE THREAD

**Issue by hjain689** [searchivarius/nmslib#224]
I am using the python wrapper for nmslib, however I couldn't find any documentation for it, apart from two small examples. Basically I want to do some parameter tuning etc. for eg. while using hnsw method I want to see what default values are being set for parameters like maxM0, maxM etc. and how can I specify these using python wrapper. Can you please provide some documentation, it will be really helpful

**Comment by searchivarius** [comment]
Hi @hjain689 we don't have a specific Python docs, there's a manual that discusses HNSW in more detail https://github.com/searchivarius/nmslib/blob/master/docs/manual.pdf

**Comment by benfred** [comment]
The Python API should have decent documentation in the docstrings on each method/class . 

I took a first pass at exposing this in this PR https://github.com/searchivarius/nmslib/pull/226 , using sphinx to build html pages and autodoc to automatically expose the docstrings from the python bindings.

You can view how this documentation looks here: https://benfred.github.io/nmslib/ The docstrings for the module are exported here https://benfred.github.io/nmslib/api.html

**Comment by hjain689** [comment]
Thanks a lot @benfred .. this is really helpful!

**Comment by searchivarius** [comment]
@benfred awesome, I am superbusy now, but I will look into this shortly. We need to update the manual + describing most important stuff online is superhelpful.

**Comment by gokceneraslan** [comment]
@benfred can you maybe add a link to https://benfred.github.io/nmslib/ in https://github.com/searchivarius/nmslib/blob/master/python_bindings/README.md file?

**Comment by searchivarius** [comment]
@benfred @gokceneraslan this needs to be eventually done by us, I mean there should be a proper github.io website. I will need to modify it tool

**Comment by hjain689** [comment]
@searchivarius is there a python function available to store (and load) the nearest neighbor model that can be loaded later to query a new set of points?

**Comment by benfred** [comment]
@hjain689 the saveIndex/loadIndex function calls will serialize the index to disk and load it back up
https://benfred.github.io/nmslib/api.html#nmslib.dist.FloatIndex.loadIndex

**Comment by hjain689** [comment]
Thanks a lot @benfred, actually when I use the saveIndex function with sparse data it gives the following error (works perfectly for dense):
RuntimeError: Storing non-optimized index is not supported yet!
Any idea as to what might be going wrong here?

**Comment by searchivarius** [comment]
@hjain689 for HNSW and non-standard (i.e) sparse spaces, saving isn't not implemented. SW-graph can save indices for sparse spaces, and it often can have similar performance.

**Comment by hjain689** [comment]
okay .. will try that out, thanks!
