### ISSUE TITLE
hnsw searchMethod Parameter

### ISSUE THREAD

**Issue by bluejay9676** [searchivarius/nmslib#225]
I couldn't find explanations on the searchMethod parameter for HNSW. I am curious if I am using the parameters in a wrong way.

```python
space_type = 'l2_sparse'
    space_param = []
    method_name = 'hnsw'
    index_name  = method_name + '_sparse.index'
    if os.path.isfile(index_name):
        os.remove(index_name)
    index = nmslib.init(space_type,
                        space_param,
                        method_name,
                        nmslib.DataType.SPARSE_VECTOR,
                        nmslib.DistType.FLOAT)
index_param = ['M=5', 'efConstruction=2000', 'indexThreadQty=56', 'searchMethod=0']
    query_time_param = ['efSearch=2000']
```
With the above code, I am achieving relatively low similarity in total (3% similarity). I was wondering if anyone can spot anything that could improve this.

**Comment by bluejay9676** [comment]
However it works fine with the sparse matrix given by the sparse_benchmark.py yielding around 98% similiarity on average.

**Comment by searchivarius** [comment]
Hi @bluejay9676 sparse_benchmark.py uses a different set of parameters and different (although similar) method SW-graph.
Shortly good efConstruction is in the range 50-300. 2000 is usually too much. M seems to small, the reasonably values of M are usually in the range of 10-50. efSearch is usually fine if selected from 100 to 2000.

We have tuning guidelines in the manual, but they are bit outdated now. We also clearly need to put them on some HTML page.

**Comment by bluejay9676** [comment]
I guess real question is:

Is the parameter I'm using accurate? (mostly searchMethod) Is searchMethod 0 corresponds to l2_sparse space type

**Comment by searchivarius** [comment]
Hi, this parameter is just for backward compatibility with ann_benchmarks. It doesn't affect anything. Sorry, we are redoing a lot of things (or planning to redo) so we don't have a truly stable-stable version yet with a complete docs.
