### ISSUE TITLE
Docs far too verbose

### ISSUE THREAD

**Issue by blutooth** [searchivarius/nmslib#227]
Why do you have 82 pages of explanation in the manual without a simple explanation of how to run tests. 
Something like ./test_run.sh giff.txt 235mb 
Why?
Why is a simple explanation of how to tun the code  not included in the readme. Someone who has just downloaded your code has to scour 80 pages of manual or dive deep into the source code to stand a chance.
I'll bet you'd have twice as many github stars if you made it easier to get started with, run straight out of the box.  
Also, document the python parameters for the python bindings...

**Comment by searchivarius** [comment]
Hi @blutooth a vast majority of people are interested only in Python bindings, manual is written for people who extend and modify the library. If you think some additional info can be added to README to make the need to scan the manual less likely, feel free to send a pull request.

Thanks!
