### ISSUE TITLE
Python bindings produce incorrect results for arrays in Fortran order

### ISSUE THREAD

**Issue by gokceneraslan** [searchivarius/nmslib#230]
I realized that I'm getting very weird results when I read numpy arrays from csv files via the `as_matrix()` function of Pandas dataframes. Then, I found out that it's because of the order the matrices are stored in memory:

```python
import nmslib as nn
import numpy as np

np.random.seed(42)
X = np.random.rand(1000, 50)

index = nn.init(method='vptree', space='l2')
index.addDataPointBatch(X)
index.createIndex()
print(index.knnQueryBatch(X, k=5)[0][0])

X2 = np.asfortranarray(X)
print(np.allclose(X, X2))

print(index.knnQueryBatch(X2, k=5)[0][0])
print(index.knnQuery(X2[0], k=5)[0])  # knnQuery works well

X3 = np.ascontiguousarray(X2)
print(index.knnQueryBatch(X3, k=5)[0][0])
```

Produces following output:

```
[  0  13 694 168 895]
True
[247 784  11 243 986]
[  0  13 694 168 895]
[  0  13 694 168 895]
```

As users may not really know about the order of the matrix, `nmslib` bindings must call `np.ascontiguousarray()` explicitly in `addDataPointBatch` and `knnQueryBatch ` without assuming that matrices are in C order.

**Comment by searchivarius** [comment]
@gokceneraslan thank you for looking into this, do I get it correctly that np.ascontigousarray() does help?

**Comment by gokceneraslan** [comment]
Yes, because it changes the order from Fortran to C.
