### ISSUE TITLE
Python addDataPointBatch bug

### ISSUE THREAD

**Issue by xueyouluo** [searchivarius/nmslib#236]
Here is the problem:

when I using the example:
```python
# create a random matrix to index
data = numpy.random.randn(10000, 100).astype(numpy.float32)

# initialize a new index, using a HNSW index on Cosine Similarity
index = nmslib.init(method='hnsw', space='cosinesimil')
index.addDataPointBatch(data)
index.createIndex({'post': 2}, print_progress=True)

# query for the nearest neighbours of the first datapoint
ids, distances = index.knnQuery(data[0], k=10)
```
the ids is :
`[   0, 8466, 9355, 5861, 1651,   18, 2474, 9736, 2172, 6289]`

***But*** when I add the data point batch by batch:
```python
for i in range(300):
    index.addDataPointBatch(data[i*30:(i+1)*30])
```
Then build the index and try knn search, the results becomes:
```python
# query for the nearest neighbours of the first datapoint
ids, _  = index.knnQuery(data[0], k=10)
ids
[ 0, 16, 12, 20,  8,  9, 12, 27, 24,  7]
```

I tried different data, the ids are all in 0-30. What happens here???

**Comment by benfred** [comment]
So addDataPointBatch takes two parameters: the data and the ids to index the data under:
https://searchivarius.github.io/nmslib/api.html#nmslib.dist.FloatIndex.addDataPointBatch

If the ids aren't set, it defaults to the row of the passed in matrix - which in your second case is always 0-30. If you set this it should work .

**Comment by searchivarius** [comment]
@benfred shouldn't we make the IDs parameter mandatory?

**Comment by xueyouluo** [comment]
@benfred Thanks for your explanation. I didn't notice the description of the ids parameter. I thought it would append the data to the previous added data.

Why do you need id here? I think usually user will add data to the index, then call the create index method when all data are added.   

You can close this issue. 

Thanks.

**Comment by searchivarius** [comment]
@xueyouluo IDs are needed, because they can be different from the insertion order.

**Comment by searchivarius** [comment]
PS: @xueyouluo but we shouldn't allow users to shoot in the feet.
