### ISSUE TITLE
Bad precision. Choosing of index parameters

### ISSUE THREAD

**Issue by Aljaksandr** [searchivarius/nmslib#240]
Hello!
I run script to evaluate precision of indexed float arrays.

```
import nmslib 
import numpy

number = 100000

data = numpy.random.randn(number, 100).astype(numpy.float32)


index = nmslib.init(method='hnsw', space='l2')
index.addDataPointBatch(data)
index.createIndex(index_params={'post': 2}, print_progress=True)


neighbours = index.knnQueryBatch(data, k=1, num_threads=4)
idxs, _ = zip(*neighbours)
idxs = numpy.vstack(idxs).ravel()
precision = sum(idxs==range(number))*100/number
print("Precision: {}%".format(precision))
```

The problem is, that I get only 57% of precision. Are there any recommendations to choose index/search parameters to increase precision with minimal time spend on query?

**Comment by searchivarius** [comment]
Hi @Aljaksandr 

it's hard to tell without the data. What is the dimensionality? Also, is there a chance that you have a lot of ties. So, some things to try:

1) Increase ef (query time parameter) and/or M (index-time parameter)
2) Try say k = 10

This low precision is especially surprising given that you search for already indexed data. In this case, the precision would be higher than for searching previously unseen data points.

**Comment by Aljaksandr** [comment]
Hi, @searchivarius 
Data are generated according numpy.random.randn() function. 100000 features x 100 floats each.
Increasing efConstruction from default 200 to 400 and M from default 16 to 32 allows reach 91.5% accuracy. But indexing takes much more time. Changing k from 1 to 10 doesn't affect.
Is it correct behavior?

**Comment by searchivarius** [comment]
@Aljaksandr methods of k-NN search don't work well for randomly generated high-dimensional data. In fact, in this case, k-NN search stops being a meaningful operation. The only useful operation for such data is a near-duplicate detection, which is usually solved using hashing approaches. For near-duplicate detection a query should be really close to the data your search .
