### ISSUE TITLE
difference between hnsw and sw-graph?

### ISSUE THREAD

**Issue by leafjungle** [searchivarius/nmslib#241]
I think I am a new comer.
I see in the benchmark: https://github.com/erikbern/ann-benchmarks, there are HNSW and SW-graph.
both of them are based on nmslib. But I am not sure the difference? And it seems hard to find the answer in Google.

**Comment by searchivarius** [comment]
Hi @leafjungle HNSW is usually better (and sometimes substantially so), but there's currently a technical deficiency that HNSW can't save indices for spaces/distances other than dense vector spaces with L2/cosine.
