### ISSUE TITLE
genplot_configurable run error

### ISSUE THREAD

**Issue by swimmingsand** [searchivarius/nmslib#242]
./genplot_configurable.py -i output_file_K=10.dat -o plot_10_NN -x 1~norm~Recall -y 1~log~ImprEfficiency -l '1~south west' -t 'Improvement in efficiency vs recall' -n MethodName -a axis_desc.txt -m meth_desc.txt
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
! I can't find file `plot_10_NN'.
<*> plot_10_NN
              
(Press Enter to retry, or Control-D to exit)
Please type another input file name:

**Comment by searchivarius** [comment]
Hi @swimmingsand would you mind sharing some how (can be over e-mail) all input files (can be over e-mail leo at boytsov.info) Would be easier for me to reproduce. Thanks!

**Comment by searchivarius** [comment]
I have to close this, b/c I have no information to reproduce the bug.
