### ISSUE TITLE
Conflicting description in the README

### ISSUE THREAD

**Issue by ijklr** [searchivarius/nmslib#246]
Under the Prerequisites section, it mentions Clang 3.4 
However, under the Limitations section, it says "HNSW does not work with Clang".

**Comment by searchivarius** [comment]
@ijklr this was true some time ago, I am going to re-test it shortly with a newer version of HNSW. Probably, this is not an issue anymore.

**Comment by searchivarius** [comment]
@ijklr thank you for noting, the dev version seems to be working fine with clang.
