### ISSUE TITLE
How to get repeatable results?

### ISSUE THREAD

**Issue by rozyang** [searchivarius/nmslib#248]
The library is very good. But I find the result is different in every run. How can I get repeatable results? Thanks.

**Comment by searchivarius** [comment]
This has two issues to it
1) Multi-threaded creation of indices
2) Use of random generators without a specific seed
While the second issue is relatively easy to fix, the first one is quite serious. Basically, if you want totally repeatable results you need to create some indices in single-threaded mode only. I suspect that HNSW should recreate mostly the same index.
There is also an issue with non-determinism of floating point operations, which might lead to slightly different results in each run, but its effect should be minor. This is not a problem that one can solve.

**Comment by searchivarius** [comment]
PS: results are repeatable in the sense that there is little difference among several runs with the same parameters.

**Comment by rozyang** [comment]
I see. Could you tell me how to fix the random seed. Then I can use single-thread to achieve pretty repeatable results. Thanks.

**Comment by searchivarius** [comment]
Ok, I am currently changing the code, it may be not so hard to do. I am closing this issue, it duplicates the previously open one #57

**Comment by searchivarius** [comment]
Ok, @rozyang this should be working in dev, but one needs to use a single thread for indexing.
