### ISSUE TITLE
Where can I find description of the python parameters?

### ISSUE THREAD

**Issue by rozyang** [searchivarius/nmslib#250]
I cannot find the description of the python parameters. In the API Reference there are only default values.  Especially, I want to know the other space names in init() except 'cosinesimil', as well as other valid index_params in createIndex() except 'post=2'. Thanks.

**Comment by searchivarius** [comment]
@rozyang will sure need to expand Python docs. So far, parameters are described only in the manual. Check, e.g., pages 58 and 63 https://github.com/searchivarius/nmslib/blob/master/manual/manual.pdf

**Comment by leafjungle** [comment]
well, In the manual.pdf, I still can not found the explanation about {"post": 2}.

**Comment by yurymalkov** [comment]
@leafjungle it is described in https://github.com/searchivarius/nmslib/issues/121

**Comment by searchivarius** [comment]
Closing and referencing from the umbrella ticket #156
