### ISSUE TITLE
difference between Ann on "non-metric space " and "metric space"

### ISSUE THREAD

**Issue by leafjungle** [searchivarius/nmslib#256]
When I read the manual: "there are fewer exact solutions for non-metric spaces". 

I know the difference between "non-metric space " and "metric space", but it is hard to understand what difficult they bring to the ann search?

**Comment by searchivarius** [comment]
Shortly, it is a much wider class of spaces with fewer nice properties.

**Comment by leafjungle** [comment]
@searchivarius , thanks for your reply.

So non-metric space will make the accurate or recall much worse? 

Or make the partitioning methods or LSH methods or Small world graph inaccurate? but why?

**Comment by searchivarius** [comment]
@leafjungle the problem is that we have well-established methods only for a bunch of spaces: some L_p, cosine/inner products and partitioning methods for metric spaces. A recent addition is a ball-tree method for Bregman divergences. Some good results can be also obtained for kernelized distances. This is basically the list of spaces which have sufficiently nice properties.

Whenever, you don't have nice properties, it's not clear mostly how to devise good (accurate and fast)  methods. There is also little empirical evidence as to which methods works in various ugly spaces.

**Comment by leafjungle** [comment]
@searchivarius 
(1)  "some L_p, cosine/inner products and partitioning methods for metric spaces"
cosine space is non-metric space, right?  it does not meets the property:  d(x,y)=0 if and only if x=y.

(2)"it's not clear mostly how to devise good (accurate and fast) methods. There is also little empirical evidence as to which methods works in various ugly spaces."

Generally in many applications, we first cluster some data by k-means, and got K clusters.
Then all the base features are clustered by the K cluster.
Then for any query feat, got the top M nearest cluster, and find the nearest result in the M cells.

Is there any experiment shows that metric-space and non-metric space makes a lot of difference(recall or accuracy) on the above solutions?

**Comment by searchivarius** [comment]
(1) cosine is not metric, but it's a pre-metric "distance" if you use 1 - cos(x,y) as the distance value. It is also symmetric. It doesn't fully satisfy the triangle inequality though.

If you use k-means, k-means should make sense in the space of interest. In particular, it should be a vector space. For non-vector spaces, k-means is not even possible. You need to use e.g. k-medoid.

Yet, talking about clustering search methods: they are not very accurate in my experience, because many data sets lack good clusters. This also applies to the Euclidean space.

**Comment by leafjungle** [comment]
@searchivarius ,  1- cos(x, 2x) = 0 but x != 2x.

Any way, So nmslib mainly focus on the non-metric space ANN.   can it be applied to the metric space ANN?

In the manual, 5 classes of search methods are listed in Page 36.  Then which one is suitable for metric space and which one is suitable for non-metric space?

And I think the clustering search methods belongs to the "LSH methods"?

**Comment by leafjungle** [comment]
The do you have any guidelines for choosing the suitable distance measurement for a given application, except the performance. ??

**Comment by searchivarius** [comment]
Yes, of course it can be used for metric spaces. All non-metric space methods work for metric spaces as well. In the next version, we will focus on developing only few best methods, so people don't have to decide what to choose. Mostly, you are good with one of the four methods: VP-tree, NAPP, SW-graph, HNSW.

**Comment by searchivarius** [comment]
PS: clustering methods are not LSH, although they can be used to build LSH-like indices.

**Comment by searchivarius** [comment]
PPS: regarding the cosine distance, it is of course supposed to be used on a set of normalized vectors.

**Comment by leafjungle** [comment]
@searchivarius  clustering methods are not LSH, although they can be used to build LSH-like indices.
-----
the clustering methods can be regarded as a LSH with a special trained hash function.  (it can also have the parameters such as hash table number/multi-probe search).

**Comment by leafjungle** [comment]
"Yes, of course it can be used for metric spaces. All non-metric space methods work for metric spaces as well. ",  but theoretical why? 

I mean,  if one distance measurement does not work very well, then we can just try another one,  and do not have to change the search method. right?

search method and distance measurement are two independent parts of ANN, right? Maybe I am not quite understand the relationship between them.

**Comment by searchivarius** [comment]
@leafjungle for most methods there're no guarantees. A metric space is just yet another non-metric space that a method is applicable too. Even if you use methods with guarantees fro metric spaces, these guarantees are either weak/vague (as in the case of LSH) or the search methods are slow (e.g., metric trees). So, you better not worry about guarantees too much as you are screwed up any way.

If one distance doesn't work well, we can sure try another one.

Search method and distance measurement are sometimes independent and sometimes are not. For example, many LSH methods are designed for specific spaces. Exact metric spaces methods work only with metric distances. We have an implementation of the ball tree for Bregman divergences. It has an exact mode. Well, needless to say this method is very much tailored to the distance. In fact, to support this search method the distance class provides additional functionality.
