### ISSUE TITLE
How to silently import nmslib?

### ISSUE THREAD

**Issue by rozyang** [searchivarius/nmslib#260]
Importing nmslib in python outputs a lot of text messages. This looks not good in, e.g. Jupyter notebook. How can I import nmslib without showing those messages?

**Comment by searchivarius** [comment]
@rozyang I need to double-check, perhaps, it just needs propagating dev to master.

**Comment by benfred** [comment]
I think we need to bump the python version (like 1.6.3 -> 1.6.4) and then push the latest version to pypi. I'm guessing that people are still installing the version without the logging changes using pip (I see the changes in master anyways).

**Comment by searchivarius** [comment]
@benfred I am working on this! There would be also improvements in saving all types of indices for HNSW and data loading speed.

**Comment by searchivarius** [comment]
It is, indeed, fine in DEV, it should be soon in the master and 1.7 release: I basically need to update the manual and some integration tests.
