### ISSUE TITLE
Issue: ./nmslib.so: undefined symbol: init

### ISSUE THREAD

**Issue by helloGitHub1993** [searchivarius/nmslib#263]
I have already install nmslib by "pip" command in my cp. I want to use nmslib in another machine but i can't use "pip" command in it. So i put nmslib.so and my script in the same directory. My code is as follows:
run.sh:
` 1 #!/bin/bash`
` 2 export LD_LIBRARY_PATH=/opt/glibc-2.14/lib:$LD_LIBRARY_PATH`
` 3 python 1.py`

1.py:
`  1 #!/usr/bin/env python`
`  2 #coding=utf-8`
 ` 3 import sys`
 ` 4 sys.path.append('./')`
`  5 import ctypes`
`  6 nmslib = ctypes.CDLL('./nmslib.so')`
 ` 7 import numpy`
`  8 data = numpy.random.randn(10000,100).astype(numpy.float32)`
 ` 9 index = nmslib.init(method='hnsw',space='cosinesimil')`
` 10 index.addDataPointBatch(data)`
` 11 index.createIndex({'post':1},print_progress=True)`
` 12 `
` 13 neighbours = index.knnQueryBatch(data,k=50)`
 `14 print neighbours[0][1]` 
OUTPUT:
`Traceback (most recent call last):`
`  File "1.py", line 9, in <module>`
`    index = nmslib.init(method='hnsw',space='cosinesimil')`
`  File "/usr/local/python_2_7_6/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__`
  `  func = self.__getitem__(name)`
 ` File "/usr/local/python_2_7_6/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__`
 `   func = self._FuncPtr((name_or_ordinal, self))`
`AttributeError: ./nmslib.so: undefined symbol: init`

**Comment by searchivarius** [comment]
Please, try to include the current directory into LD_LIBRARY_PATH. You can also use LD_PRELOAD I believe.

**Comment by helloGitHub1993** [comment]
I used `export LD_LIBRARY_PATH=/opt/glibc-2.14/lib:$LD_LIBRARY_PATH:/data10/cd1/gy/nmslib` and output is still the same:
`Traceback (most recent call last):`
`  File "1.py", line 11, in <module>`
 `   index = nmslib.init(method='hnsw',space='cosinesimil')`
  `File "/usr/local/python_2_7_6/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__`
   ` func = self.__getitem__(name)`
 ` File "/usr/local/python_2_7_6/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__`
  `  func = self._FuncPtr((name_or_ordinal, self))`
`AttributeError: ./nmslib.so: undefined symbol: init`

**Comment by searchivarius** [comment]
It's a weird error, I am afraid you need to recompile the library on this machine.

**Comment by helloGitHub1993** [comment]
I use "pip" command to install the nmslib. And then i can get nmslib.so in lib64/python2.7/site-pachages/. Is that the cause?

**Comment by searchivarius** [comment]
You previously reported that you cannot use pip

**Comment by helloGitHub1993** [comment]
I mean i used pip in machine A and got the nmslib.so. But now i want to use nmslib in machine B and i cannot use pip in B.

**Comment by searchivarius** [comment]
Right this is what I thought, try to properly recompile please on machine B. It is in principle possible, but the environment should be the same. Same libraries, same OS, same version of Python and god knows what else may go wrong...

**Comment by helloGitHub1993** [comment]
OK.Thank you for your patience.
