### ISSUE TITLE
Python wrapper crashes while retrieving nearest neighbors when M>100

### ISSUE THREAD

**Issue by hjain689** [searchivarius/nmslib#264]
Hi,
I am working on a problem where I need to retrieve ~500 nearest neighbors out of a million points. I am using the python wrapper for HNSW method. The code works perfectly well if I set the value of parameter M <=100 but setting it greater than 100, the code crashes during retrieving nearest neighbors (no issues while building the model) with an "invalid next size" error. Any idea why this might be happening?
Thanks
Himanshu

**Comment by searchivarius** [comment]
Well, ideally I would need a reproducible example. Is it possible to reproduce using some existing, perhaps, random data?

**Comment by hjain689** [comment]
sure, I'll try and create an example

**Comment by hjain689** [comment]
hi.. I have created an example. The data is slightly big (~800mb), my apologies for that. You can download the data from here - https://drive.google.com/open?id=1xq67SodKBZe_FMzMs1XfQCxBOpJ7v1KB
Following is the code that I am using to build the kNN model and test it. For the time being, I am finding the nearest neighbors of the points already present in the graph. The code crashes while querying -


import numpy
import sys
import nmslib
import time
import math

data_file = 'cent_mat_dense_bin'
M = 200
efC = 400
efS = 400
num_nbrs = 400
num_thread = 4

fp = open(data_file,'rb')
fp.seek(8)
data = numpy.fromfile(fp,dtype=numpy.float32,count=-1,sep='')
data = numpy.reshape(data,(len(data)/300,300))
end = time.time()
print 'num_inst = %d'%int(data.shape[0])
start = time.time()
index = nmslib.init(method='hnsw', space='cosinesimil')
index.addDataPointBatch(data)
index.createIndex({'M': M, 'indexThreadQty': num_thread, 'efConstruction': efC})
end = time.time()
print 'Training time = %f'%(end-start)
index.setQueryTimeParams({'efSearch': efS})

print 'Testing....'
start = time.time()
nbrs = index.knnQueryBatch(data, k=num_nbrs, num_threads = num_thread)
end = time.time()

**Comment by searchivarius** [comment]
Thank you, 800 MB is totally fine.

**Comment by hjain689** [comment]
Just wanted to know if you were able to reproduce the error!!

**Comment by searchivarius** [comment]
Hi @hjain689 I am playing with it, thanks!

**Comment by searchivarius** [comment]
Hi @hjain689 I nearly nailed, but fixing could take time (it is a nasty thing). As a workaround you can use the following query parameters (add algoType = old):
```
index.setQueryTimeParams({'efSearch': efS, 'algoType': 'old'})
```

**Comment by hjain689** [comment]
Hey @searchivarius thanks a lot! Does using algoType = old affect the performance(in terms of accuracy or time taken) in any way?
Do let me know when you fix the bug.

**Comment by searchivarius** [comment]
@hjain689 for small efSearch  speed can decrease a bit, but not much, say 10-20%. If vectors are long say dim=300, the diff is rather small already.

**Comment by hjain689** [comment]
A few more questions, would be really helpful if you could please answer them -
1) Since HNSW starts with a random initialization, I was wondering if its possible to specify random number seed while training the hnsw graph? Basically I want to create multiple graphs with different random initializations
2) Which method do you think would be the best if my data is high dimensional sparse say million dimensional with ~300 non zeros? I tried hnsw but the performance wasn't very good and it was very slow too

**Comment by searchivarius** [comment]
@hjain689 
1. Is in process
2. Regarding performance: could I try your data? In some cases NAPP with generated pivots could be better. In any case, I would love to see the data where HNSW doesn't perform well

Thank you!

**Comment by hjain689** [comment]
sure i'll send u the data

**Comment by searchivarius** [comment]
Ok, I think I fixed the issue with crashing. https://github.com/searchivarius/nmslib/commit/aa6816c5c98bf422fcf75d2d3b835d26f871f39a
I will fix the random initialization issue next.
BTW, @hjain689 feel free to share the data!

**Comment by hjain689** [comment]
thanks a lot! sorry I forgot about the data. Actually, you can directly download these from our repository page http://manikvarma.org/downloads/XC/XMLRepository.html 
These are essentially multi-label learning datasets, for knn experiments you can ignore the label matrix and just take the feature matrix.

**Comment by searchivarius** [comment]
@hjain689 great!
1) which data set was problematic? 
2) what parameters did you try and what was approximately an outcome (recall and speed up)?
3) what is k in the k-nn search?
I need to know what my baseline is.
Thank you!

**Comment by hjain689** [comment]
I will send you a specific example where it was taking too much time and performance was not that good either.

**Comment by searchivarius** [comment]
@hjain689 thanks, this will be very useful!

**Comment by hjain689** [comment]
@searchivarius I have uploaded the sparse datasets at -
Training points(321K, 1.6M dimensional sparse) - https://drive.google.com/file/d/1aW4FmF46FsGMwi_AJzYJW8jD6yHtYO2u/view?usp=sharing
Test points - https://drive.google.com/open?id=115U3QrQUapmGv9mQJKYBFqGNRRCnp5Lk
The script I am using to find nearest neighbors is appended below. It is taking forever to train and the performance is not good as well. Would be great if you could have a look -

import numpy 
import sys 
import nmslib 
import time 
import math 
from scipy.sparse import csr_matrix 
def read_data(filename): 
    row = [] 
    col = [] 
    data = [] 
    i = 0 
    with open(filename,'r') as f: 
        x = next(f) 
        x = x.strip('\n').split(' ') 
        num_inst = int(x[0]) 
        num_ft = int(x[1]) 
        for line in f: 
            x = line.strip('\n').split(' ') 
            for ft in x: 
                ft = ft.split(':') 
                if len(ft)<2: 
                    continue 
                row.append(i) 
                col.append(int(ft[0])) 
                data.append(float(ft[1])) 
            i = i+1 
    ft_mat = csr_matrix((numpy.array(data), (numpy.array(row), numpy.array(col))), shape=(num_inst, num_ft)) 
    return ft_mat 
             
lbl_ft_file = 'cent_mat.txt' 
ft_file = 'tst_mat.txt' 
M = 100 
efC = 300 
efS = 300 
num_nbrs = 300 
write_dist = 1 
out_file = 'output.txt' 
 
start = time.time() 
data = read_data(lbl_ft_file) 
end = time.time() 
print 'lbl_ft_mat Read time = %f'%(end-start) 
 
start = time.time() 
index = nmslib.init(method='hnsw', space='cosinesimil_sparse', data_type=nmslib.DataType.SPARSE_VECTOR) 
index.addDataPointBatch(data) 
index.createIndex({'M': M, 'indexThreadQty': 1, 'efConstruction': efC}) 
end = time.time() 
print 'Training time = %f'%(end-start) 
 
index.setQueryTimeParams({'efSearch': efS}) 
print('Training done ...') 
 
 
query = read_data(ft_file) 
start = time.time() 
nbrs = index.knnQueryBatch(query, k=num_nbrs, num_threads = 1) 
end = time.time() 
print('kNN Time = %f'%(end-start)) 
 
with open(out_file,'w') as fp: 
    fp.write('%d %d\n'%(len(nbrs),len(data))) 
    if write_dist == 1: 
        for j in range(0,len(nbrs)): 
            temp = {} 
            flag = 0 
            for k in range(0,len(nbrs[j][0])): 
                temp[nbrs[j][0][k]] = 1-nbrs[j][1][k] 
            for t in sorted(temp): 
                if flag ==0: 
                    fp.write('%d:%f'%(t,temp[t])) 
                    flag = 1 
                else: 
                    fp.write(' %d:%f'%(t,temp[t])) 
            fp.write('\n') 
    else: 
        for j in range(0,len(nbrs)): 
            temp = {} 
            flag = 0 
            for k in range(0,len(nbrs[j][0])): 
                temp[nbrs[j][0][k]] = 1 
            for t in sorted(temp): 
                if flag ==0: 
                    fp.write('%d'%(t)) 
                    flag = 1 
                else: 
                    fp.write(' %d'%(t)) 
            fp.write('\n')

**Comment by searchivarius** [comment]
@hjain689 thanks! I tested a sample (100K data points and 10K queries) using our binary. It seems to be working really well for M=30, efConstruction100, and ef=250. I haven't tested Python bindings yet, but I wonder how do you test **the quality of the output**, i.e., what is the test script that checks quality?

**Comment by searchivarius** [comment]
@hjain689 BTW, I think for best results you may need to shuffle data. This seems to be quite similar to the Wikipedia data: you get a lot of long entries in the beginning, but most of the entries are quite short. Whether shuffling helps or not, of course, is an empirical question, but it might.

**Comment by hjain689** [comment]
Ohk ... I am not doing that! 
will do it but the training is taking more than an hour, is that expected?

**Comment by searchivarius** [comment]
Hi @hjain689 I haven't check if this helps or not. However, I do get Ok results (certainly not bad one) with a subset of your data. I checked the results against brute-force search (see the attached script) the accuracy is quite high:
```
Read 50000 rows (out of 321222), maxim # of features 1617898 (out of 1617899)
Data reading time = 53.602128
Data shape (50000, 1617899)
Index-time parameters {'indexThreadQty': 4, 'M': 30, 'efConstruction': 100}
Indexing time = 167.707027
Indexing done ...
Setting query-time parameters {'efSearch': 300}
Read 5000 rows (out of 587084), maxim # of features 1617894 (out of 1617899)
Query shape (5000, 1617899)
kNN time total=17.564150 (sec), per query=0.003513 (sec), per query adjusted for thread#=0.014051
Computing gold-standard data
Brute-force preparation time 0.098935
brute-force kNN time total=26.729044 (sec), per query=0.005346 (sec)
kNN recall 0.912534
```
Now, the following notes:
1. I use somewhat "lighter" indexing parameters and multiple threads for indexing. For your data set, you certainly don't need such high values of M and efConstruction. 
2. Because of multi-threading, the results are never fully reproducible, but the variance (from run to run) is not big. You can also save/load index. I created Python 3 notebooks with detailed usage examples: https://github.com/searchivarius/nmslib/tree/develop/python_bindings/notebooks. For the given saved index results should be reproducible.
3. sklearn brute-force is suspiciously fast, but it's also very memory greedy. I think it creates some sort of memory-inefficient index for fast intersection. 
4. shuffling might help, but I didn't check results.

**Comment by searchivarius** [comment]
Uuuups, sorry @hjain689 forgot to attach my version of your script.
[test_sparse.py.gz](https://github.com/searchivarius/nmslib/files/1629072/test_sparse.py.gz)

**Comment by searchivarius** [comment]
Or simply copy-paste:
```
#!/usr/bin/env python3
import numpy 
import sys 
import nmslib 
import time 
import math 
from scipy.sparse import csr_matrix 
from sklearn.neighbors import NearestNeighbors

def read_data(filename, max_qty): 
    row = [] 
    col = [] 
    data = [] 
    read_qty = 0 
    with open(filename,'r') as f: 
        x = next(f) 
        x = x.strip('\n').split(' ') 
        
        total_qty = int(x[0]) 
        total_num_ft = int(x[1]) 
        read_num_ft = 0
        for line in f: 
            x = line.strip('\n').split(' ') 
            for ft in x: 
                ft = ft.split(':') 
                if len(ft)<2: 
                    continue 
                row.append(read_qty) 
                feat_id = int(ft[0])
                read_num_ft = max(read_num_ft, feat_id + 1)
                col.append(feat_id) 
                data.append(float(ft[1])) 

            read_qty = read_qty+1 
            if read_qty >= max_qty:
              break
            
    print('Read %d rows (out of %d), maxim # of features %d (out of %d)' % 
          (read_qty, total_qty, read_num_ft, total_num_ft))
    ft_mat = csr_matrix((numpy.array(data), (numpy.array(row), numpy.array(col))), 
                         shape=(read_qty, total_num_ft)) 
    return (read_qty, ft_mat)
             
lbl_ft_file = 'cent_mat.txt' 
ft_file = 'tst_mat.txt' 

M = 30
efC = 100
efS = 300 

num_threads = 4

num_nbrs = 300 

#max_num_data = 10000
#max_num_query = 10000
#max_num_data = sys.maxsize
max_num_data = 50000
# Don't use a large number of queries
# or else brute-force will run out of memory!
max_num_query = 5000
 
start = time.time() 
(data_qty, data_matrix) = read_data(lbl_ft_file, max_num_data) 
end = time.time() 
print('Data reading time = %f' % (end-start) )
print("Data shape", data_matrix.shape)
 
start = time.time() 
index = nmslib.init(method='hnsw', space='cosinesimil_sparse', data_type=nmslib.DataType.SPARSE_VECTOR) 
index.addDataPointBatch(data_matrix) 
index_time_params = {'M': M, 'indexThreadQty': num_threads, 'efConstruction': efC}
index.createIndex(index_time_params) 
end = time.time() 
print('Index-time parameters', index_time_params)
print('Indexing time = %f' % (end-start))
 
print('Indexing done ...') 
query_time_params = {'efSearch': efS}
print('Setting query-time parameters', query_time_params)
index.setQueryTimeParams(query_time_params) 
 
(query_qty, query_matrix) = read_data(ft_file, max_num_query) 
print("Query shape", query_matrix.shape)
start = time.time() 
nbrs = index.knnQueryBatch(query_matrix, k = num_nbrs, num_threads = num_threads)
end = time.time() 
print('kNN time total=%f (sec), per query=%f (sec), per query adjusted for thread#=%f' % 
      (end-start, float(end-start)/query_qty, num_threads*float(end-start)/query_qty)) 

print('Computing gold-standard data')

start = time.time()
sindx = NearestNeighbors(n_neighbors= num_nbrs, metric='cosine', algorithm='brute').fit(data_matrix)
end = time.time()

print('Brute-force preparation time %f' % (end - start))

start = time.time() 
gs = sindx.kneighbors(query_matrix)
end = time.time()

print('brute-force kNN time total=%f (sec), per query=%f (sec)' % 
      (end-start, float(end-start)/query_qty) )

recall=0.0
for i in range(0, query_qty):
  correct_set = set(gs[1][i])
  ret_set = set(nbrs[i][0])
  recall = recall + float(len(correct_set.intersection(ret_set))) / num_nbrs
recall = recall / query_qty


print('kNN recall %f' % recall)

```

**Comment by hjain689** [comment]
Thanks a lot @searchivarius .. this is really helpful, will do some experiments on my side and let you know the performance
Thanks again :)
