### ISSUE TITLE
Fixed-radius near neighbors

### ISSUE THREAD

**Issue by Burning-Daylight** [searchivarius/nmslib#265]
Is there a way to perform approximate near neighbors search within a given radius as opposed to the fixed k? Like radiusSearch in FLANN?

**Comment by searchivarius** [comment]
Hi, we can do it, but basically only for VP-tree that works really well only in low dimensions. And AFAIK this is not for Python API.

**Comment by Burning-Daylight** [comment]
Sorry, do you mean, that only for VP-tree it will work really well or that in the case of VP-tree it will work only in low dimensions? Do you think it will work worse than FLANN version for d=5-20?

**Comment by searchivarius** [comment]
I mean that
1) Range search is supported only by a bunch of methods (although I do plan to extend graph-based search methods to support it)
2) It is not available to Python API.

Regarding comparison to FLANN: for d=5-20 it could be pretty efficient for many datasets, but I don't think it will beat FLANN.

**Comment by searchivarius** [comment]
How essential is range search? Can you approximte it as k-NN search with k learned from data?

**Comment by Burning-Daylight** [comment]
I guess it won't work because the k will be to point-specific.
Is the range search supported by the C++ API already? Where could I learn about it? Only the sources?

**Comment by searchivarius** [comment]
@Burning-Daylight in this case, it won't.

We have sample apps: https://github.com/searchivarius/nmslib/blob/master/sample_standalone_app/sample_standalone_app1.cc#L241

**Comment by searchivarius** [comment]
I am closing this, b/c there are related open issues: #117 and #130
