### ISSUE TITLE
#include"string.h" in distcomp_lp.cc

### ISSUE THREAD

**Issue by Fdhvdu** [searchivarius/nmslib#266]
Hello,
This is not bug.
I am merely curious about the Line 17 in distcomp_lp.cc.
https://github.com/searchivarius/nmslib/blob/master/similarity_search/src/distcomp_lp.cc#L17

Should it be `#include<string.h>` or `#include<cstring>`?

By the way, I cannot find any function which is related to `strcpy` or `memcpy` in this file.

**Comment by searchivarius** [comment]
Thank you, it is a good reminder not to mix old-style functions. This include wasn't even needed. I committed a change to dev.
