### ISSUE TITLE
Python HNSW Segmentation Fault

### ISSUE THREAD

**Issue by GreenSlime96** [searchivarius/nmslib#279]
Hi,

I am trying to use this library to perform KNN on approximately 13 million SIFT vectors, with the expectation that more will be required in the future.

I've been getting segmentation faults running this code with the full 13 million vectors, and it faults when I try it with 10 million too.

The machines I test on are running Ubuntu 16.04, Python 3.5, with 32GB of RAM and a 6C/12T core i7. Any idea way I can debug this?

Additionally I am using hnsw l2, creating the index with M=2, post=2, efConstruction=400.

Many thanks!

**Comment by searchivarius** [comment]
Hi @GreenSlime96 could you post the Python code that you use? Thanks!

**Comment by GreenSlime96** [comment]
Hi @searchivarius,

Apologies for the lack of detail, was very early in the morning when I received notification of the segfault. I am working with circa 15 million 128-dimensional SIFT vectors.

```
index = nmslib.init(method='hnsw', space='l2')
index.addDataPointBatch(np.random.randn(15000000, 128).astype(np.float32))
index.createIndex(dict(M=20, post=2, efConstruction=400), True)

2018-02-02 14:03:44 hnsw.cc:178 (CreateIndex) [INFO] M                   = 20
2018-02-02 14:03:44 hnsw.cc:179 (CreateIndex) [INFO] indexThreadQty      = 12
2018-02-02 14:03:44 hnsw.cc:180 (CreateIndex) [INFO] efConstruction      = 400
2018-02-02 14:03:44 hnsw.cc:181 (CreateIndex) [INFO] maxM                                 = 20
2018-02-02 14:03:44 hnsw.cc:182 (CreateIndex) [INFO] maxM0                                = 40
2018-02-02 14:03:44 hnsw.cc:184 (CreateIndex) [INFO] mult                = 0.333808
2018-02-02 14:03:44 hnsw.cc:185 (CreateIndex) [INFO] skip_optimized_index= 0
2018-02-02 14:03:44 hnsw.cc:186 (CreateIndex) [INFO] delaunay_type       = 2
2018-02-02 14:03:44 hnsw.cc:449 (SetQueryTimeParams) [INFO] Set HNSW query-time parameters:
2018-02-02 14:03:44 hnsw.cc:450 (SetQueryTimeParams) [INFO] ef(Search)         =20
2018-02-02 14:03:44 hnsw.cc:451 (SetQueryTimeParams) [INFO] algoType           =2
```

I don't get past the point of creating optimised indexes.

Thanks for looking into this.

**Comment by searchivarius** [comment]
@GreenSlime96 thanks, no worries! Also which version do you use? master,  latest from PiPy, or dev?

**Comment by GreenSlime96** [comment]
I'm using the version available on pip for Python 3:

```
nmslib==1.6.3
pybind11==2.2.1
```

I'm currently running more tests, the indexes seem to work for 5M so far. I am running the 15M again and will post a more descriptive error output later when it's done.

**Comment by searchivarius** [comment]
@GreenSlime96 how much memory does 5M use on your machine?

**Comment by GreenSlime96** [comment]
@searchivarius I saved the indexes onto disk and the memory consumption for 5M is 3.3G

**Comment by searchivarius** [comment]
@GreenSlime96 it can be a bit misleading, could you see how much the process uses? Python adds its own footprint as well and there's currently some other source of unnecessary memory duplication :-( BTW, for most purposes efConstruction=100 is good enough. using efConstruction=100 makes things much faster.

**Comment by GreenSlime96** [comment]
The process uses 3.616GB of memory, after I load the index using `loadIndex('5M.hnsw')`. Unfortunately the process was killed when testing with the 15M randomly-generated 128d vectors. I will try it with your parameters, I'm basing them off the ann-benchmarks for SIFT.

I am curious if it will be trivial to add l2-support for 8-bit unsigned integers -- the SIFT vectors are 8-bit 128d and I think a significant memory reduction can be achieved using a compact representation.

```
2018-02-02 23:22:05 hnsw.cc:752 (LoadIndex) [INFO] Loading index from 5M.hnsw
2018-02-02 23:22:05 hnsw.cc:770 (LoadIndex) [INFO] searchMethod: 3
2018-02-02 23:22:05 hnsw.cc:780 (LoadIndex) [INFO] Total: 5000000, Memory per object: 692
2018-02-02 23:22:25 hnsw.cc:800 (LoadIndex) [INFO] Finished loading index
2018-02-02 23:22:25 hnsw.cc:449 (SetQueryTimeParams) [INFO] Set HNSW query-time parameters:
2018-02-02 23:22:25 hnsw.cc:450 (SetQueryTimeParams) [INFO] ef(Search)         =20
2018-02-02 23:22:25 hnsw.cc:451 (SetQueryTimeParams) [INFO] algoType           =2

```

**Comment by searchivarius** [comment]
Hi @GreenSlime96 thanks a lot for the detailed information! I think I know what's happening. I am pretty sure it's a memory issue. The older version uses malloc without checking it's return value. :-( You can try building a non-optimized index with the additional option skip_optimized_index=1. The retrieval speed will be affected but not by a lot. In the future, we will still be able to build the optimized index using less memory.

Regarding memory footprint reduction with the current version:
1) How do you load data? Do you first load into Python? If you load all the data at once, this is quite an overhead, b/c NMSLIB creates a copy of the data. If you load data in chunks and call addDataPointBatch for each chunk, this would be more space-efficient.
2) Storing SIFT data compactly is possible with some work, but will many people benefit from this? My impression is that everybody uses deep descriptors nowadays.

**Comment by GreenSlime96** [comment]
Thanks for the suggestion @searchivarius. Right now I've saved the Numpy array onto disk, and load it up within the `addDataPointBatch`, so something like this `addDataPointBatch(np.load('features')`. I think the memory overhead with this is insignificant as (I believe) Python GCs the array once the function-call returns. I could give it a shot.

Regarding SIFT. I've been looking into other implementations (such as FLANN and Annoy) and the general gist seems to be that storing vectors of `uint8` is not supported by the Euclidean distance function --- even in `nmslib` its only supported by `FloatIndex` and `DoubleIndex`. Is it possible to have l2 for `uint8`? I'm staying with SIFT as I need to work with local descriptors, whereas deep descriptors are mostly global representations.

Finally, you mention older, current, and newer versions. Would cloning the repository and (attempting) to build from source fix the segmentation fault? I just need the index to be built on a machine, which I will then save and use on other machines (which I think the pip-installed v1.6.3 would suffice).

Many thanks!

**Comment by searchivarius** [comment]
Hi @GreenSlime96 regarding the files. Perhaps, Python collects memory. You may want to double-check though. I think it might be helpful to do two things:
1) Use mmap_mode in np.load
2) Explicitly call the garbage collector.

Regarding SIFT, it is possible. Actually, if this could be useful, I would rather add it now (it's not much work). One catch though that with this kind of space there will be no optimized index (which has some drawbacks).

Regarding segfault: if only creation of optimized index crashes, you have enough memory for non-optimized index. So, even right now you should be able to use this with two additional tweaks:
1) Specify skip_optimized_index=1
2) Reload all data before loading unoptimized index (the optimized index saves both data and the meta-index).

Meanwhile, I will add the L2-uint8 space, which would permit a much smaller memory footprint. Should not take me much.

**Comment by GreenSlime96** [comment]
Hey @searchivarius, thanks so very much for the excellent input. I noticed that PyPi has updated to 1.7, which I tried earlier. Now this results in (without skip_optimised_index = 1):

```
asdCheck failed: data_level0_memory_
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-de00f516a78d> in <module>()
----> 1 index.createIndex(dict(M=20, post=2, efConstruction=400), True)

RuntimeError: Check failed: it's either a bug or inconsistent data!
```

Strangely enough I've tried adding `skip_optimised_index = 1` to the latest index-creation, however it seems to always be killed by the OS for taking too much memory. I am currently investigating this (killed thrice already) and will update you tomorrow.

**Comment by searchivarius** [comment]
@GreenSlime96 SIFT has always 128 elements, right?

**Comment by GreenSlime96** [comment]
Yep, that's right. I think you were right in that it's a memory issue, I don't get segmentation faults when trying to build indexes now. Will see if I can get hold of more memory.

**Comment by searchivarius** [comment]
@GreenSlime96 ok then, you will need a bit less of it with L2sift. Hold on tight!

**Comment by GreenSlime96** [comment]
@searchivarius Glad to hear this, thanks so much for your invaluable advice here :-) It's no rush, I managed to get the optimised index working on all 15M vectors using a machine with much higher memory. I do look forward to using the uint8-optimised version once this project expands to a wider coverage though, as the lower memory-requirements will definitely be useful.

**Comment by searchivarius** [comment]
Hi @GreenSlime96 no worries, I actually want this to be done ASAP while I am working on a new release. Here's a new ticket: ##280. I would rather not make an optimized index for the SIFT/L2 space, so the search speed is somewhat worse, but space savings are nice (and index construction is faster). So for M=20 and SIFT I get a 2x reduction in memory use. 

This is all currently done at the C++ level, but I will update Python bindings quite soon too.

**Comment by searchivarius** [comment]
Hi @GreenSlime96 please note that I have updated the Python bindings code, so if you create a pull request, make sure you do this from the latest develop branch. BTW, these are changes for the new space efficient SIFT space. It seems to be all working. However, I am going to carry out a more thorough test tomorrow. A sample Python notebook is here:
https://github.com/searchivarius/nmslib/blob/develop/python_bindings/notebooks/search_sift_uint8.ipynb
