### ISSUE TITLE
Out of memory while loading index

### ISSUE THREAD

**Issue by calz1** [searchivarius/nmslib#284]
I am trying to load an index from file within an AWS Lambda function. Right before the process abruptly terminates, I see:

> 2018-02-10 02:26:29 hnsw.cc:752 (LoadIndex) [INFO] Loading index from /tmp/index.idx
> 2018-02-10 02:26:29 hnsw.cc:770 (LoadIndex) [INFO] searchMethod: 12884901890
> 2018-02-10 02:26:29 hnsw.cc:780 (LoadIndex) [INFO] Total: 1, Memory per object: 2645699871332

Does this mean it tried to allocate 2.6TB of memory? I only have about 24,000 IDs in my index.

**Comment by searchivarius** [comment]
Please provide details: version, type of data, how the index was created and loaded to reproduce this.
thanks!

**Comment by calz1** [comment]
Thanks for the quick response! 

I am using v1.7 because I recently created a new virtual environment. I am not sure if that is relevant but this problem only started happening in the last week so it might be related.

The data is 24K records with the 1D vectors being ~121 items in length.

```
##Building process
import nmslib
index = nmslib.init( space='l2')

for item in clean_list:
    ix_array = []
    #populate ix_array with long vector 
	#....
	
	#item_id is an integer, roughly from 0 to 24K. There are gaps in the sequence
    res = index.addDataPoint(id = item['item_id'],data = ix_array)
    
index.createIndex({'post': 2}, print_progress=True)
index.saveIndex('/tmp/nms.idx')


```
The above works fine, because I see:

> 
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> 
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> 

###Querying
```


import nmslib

nmslib_index = nmslib.init(space='l2') 
print('about to load index')
nmslib_index.loadIndex('/tmp/index.idx')
#process exits right here ^^^

	

```

**Comment by mug31416** [comment]
Are you sure you load the index created by version 1.7? In your example you save to /tmp/nms.idx and load from /tmp/index.idx. 1.7 index isn't binary compatible with older index versions.

**Comment by searchivarius** [comment]
Hi @calz1 are you sure you load the index created by 1.7? From your code you save to /tmp/nms.idx, but load /tmp/index.idx

**Comment by calz1** [comment]
That was it! I actually have a VM building the index separately and it was one nmslib version back. As soon as I pip upgraded it, the error went away. Thanks for the help.

Maybe to prevent other dummies like me from running into this, you could put a version identifier into the index file and throw an exception if someone tries to load an incompatible index file?

**Comment by searchivarius** [comment]
@calz1 great thanks for checking. This is unfortunately a remind that our serialization process is quite bad, we will need to fix it some day.
