### ISSUE TITLE
Question: Product Quantization

### ISSUE THREAD

**Issue by zommerfelds** [searchivarius/nmslib#288]
Hi,

I'm not sure how this fits with all the methods you guys have implemented but I was curious if you support methods based on Product Quantization?

[Product quantization for nearest neighbor search](https://lear.inrialpes.fr/pubs/2011/JDS11/jegou_searching_with_quantization.pdf)
[Locally Optimized Product Quantization for Approximate Nearest Neighbor Search](http://image.ntua.gr/iva/files/lopq.pdf)

Cheers

**Comment by searchivarius** [comment]
Hi @zommerfelds we don't support quantization approaches.
