### ISSUE TITLE
getting a bunch of compilation error while installing nmslib's python bindings on amazon AMI

### ISSUE THREAD

**Issue by asdspal** [searchivarius/nmslib#293]
I'm trying to install nmslib on my amazon ec2 instance. I had to manually link `cc1plus`. I'm getting errors like this 
`cc1plus: error: unrecognized command line option ‘-mno-sha’`

gcc - version : 4.8.5

Any ideas how to resolve this?

**Comment by searchivarius** [comment]
Which Amazon AMI instance?

**Comment by asdspal** [comment]
I'm using Deep Learning AMI (Amazon Linux) Version 4.0 - ami-fb0f8b83

**Comment by searchivarius** [comment]
And how do install the library? pypi, local build, etc?

**Comment by asdspal** [comment]
using pip. Right now I'm trying to update the gcc and see if it resolves the error.

**Comment by searchivarius** [comment]
Please, try to install it locally. First, do
cmake .
make -j 10
Then try to run
sudo python build install
from python_bindings
AFAIK, it is hard to make ptyhon setup tools to work everywhere :(

**Comment by searchivarius** [comment]
PS: git clone ...
before doing any of this.

**Comment by asdspal** [comment]
solved it. My system had three versions of gcc (4.8.5, 6.2, 7) and default was gcc-7. When I changed it to 4.8.5, I was able to compile and install the nmslib. Thanks for your help

**Comment by searchivarius** [comment]
Hi @asdspal thank you for taking the time to investigate it! This was really helpful.
