### ISSUE TITLE
Question about incremental addition for sw-graph and hnsw

### ISSUE THREAD

**Issue by lzuwei** [searchivarius/nmslib#296]
Does this 2 models support incremental additions of new items to created indexes. If so how will knn search performance change with new items?

Any advise is appreciated!

**Comment by searchivarius** [comment]
The model supports, but software doesn't fully support. For SW-graph, though you can use C++ API do do **both** insertions and deletions:
https://github.com/searchivarius/nmslib/blob/master/test_batch_app/test_batch_mod.cc
The effect on performance isn't clear:
1) The accuracy seems to be quite stable if you delete something and add something.
2) When you add data points efficiency generally decreases, but usually quite gracefully. Obviously, you would need to use the larger value of efSearch to achieve the same accuracy as before.
