### ISSUE TITLE
Manual v1.5 Section 2.6 out of date

### ISSUE THREAD

**Issue by JoshuaBeard** [searchivarius/nmslib#297]
The Manual v1.5 contains some presumably out-of-date information. It states that "To build bindings for dense vector spaces... build the library first. Then, change the directory to `python_vect_bindings` and type...".

A quick search showed me that there is no directory called `python_vect_bindings` in the `master` or `develop` branches. I know that this manual does not yet reflect the current status of the repo, but thought you should be aware of this.

![latest-screenshot](https://user-images.githubusercontent.com/16946477/37161533-f8d0b5a4-22c0-11e8-8f1d-2632022d64c5.png)

**Comment by searchivarius** [comment]
It's not just some, it's a lot and we state it :-). There is a separate ticket for this to update/simplify the manual. But bindings have now a decent description in the Wiki: https://github.com/searchivarius/nmslib/tree/master/python_bindings
