### ISSUE TITLE
Use getDataPoint and getDataPointQty on loaded index

### ISSUE THREAD

**Issue by rbrthogan** [searchivarius/nmslib#298]
The functions `getDataPoint` and `getDataPointQty` work as expected when I am creating an index from scratch, but if I save the index to disk and load in different session `getDataPointQty` returns 0, and `getDataPoint` throws and error i.e. calling
```
index.getDataPoint(0))
```
gives
```
AttributeError: 'nmslib.dist.FloatIndex' object has no attribute 'getDataPoint'
```

Any ideas? or is this a known limitation of saving/loading

**Comment by searchivarius** [comment]
Currently, these are mostly meta-indices (so, yes, it's the limitation). You have to reload data to get data points, see, e.g., here: https://github.com/searchivarius/nmslib/blob/master/python_bindings/notebooks/search_dense_nonoptim.ipynb
At some point, I play to make saving function to save data as well (as many people expect), but not in the current version.

**Comment by rbrthogan** [comment]
ok thanks for the quick response @searchivarius

**Comment by searchivarius** [comment]
@rbrthogan no problem, hopefully, we will fix in the next major release.
