### ISSUE TITLE
Add a feature to the exists index

### ISSUE THREAD

**Issue by zpmmehrdad** [searchivarius/nmslib#299]
Hi,
How can I add a feature to exist my index in python?

**Comment by searchivarius** [comment]
Hi @zpmmehrdad if you are asking about increasing dimensionality of input vectors, this is not possible. Furthermore, I don't think it's worth a support. However, one can use sparse vectors with the large enough dimensionality. Please, use https://gitter.im/nmslib/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge for these kind of discussions. Thank you!

**Comment by zpmmehrdad** [comment]
Hi @searchivarius, Thanks for response in fact my problem is that i created a index with 10,000 features and now I wanna add another feature to the index.i don't want to create an index again.is it possible?

**Comment by searchivarius** [comment]
@zpmmehrdad unfortunately, it is not, sorry. It is also not clear how to include additional features. Adding a single feature can change a lot.

**Comment by zpmmehrdad** [comment]
So what can I do?
I have a large dataset almost 50,000,000 records and every day it's getting big.it's mean I have to create an index every day!

**Comment by searchivarius** [comment]
Hi @zpmmehrdad I can feel your pain, but there is really no way to do this. Again, remember that adding a single feature can change everything. How do propose to deal this issue in a generic fashion?

**Comment by zpmmehrdad** [comment]
Hi @searchivarius can I merge several indexes into one?
in your opinion what is the best solution for my problem?
Thnaks

**Comment by searchivarius** [comment]
@zpmmehrdad in principal it is possible, but we don't support it and doing so properly is an open research problem :-)

**Comment by yurymalkov** [comment]
@zpmmehrdad I wonder, do you mean you what to append new data, not features (changing number of features =  changing dimensionality of the vectors)?

**Comment by zpmmehrdad** [comment]
Hi @yurymalkov I mean, I have a large dataset of vectors about 50,000,000 (each record is 4096 dimension) and I want to create an index once and after that, I add another feature to the index because my dataset is growing every day. I understood that I should create an index every time.
what should I do?

**Comment by searchivarius** [comment]
Hi @zpmmehrdad we don't currently support *ANY* updates, except for SW-graph (which is slower than HNSW). However, we are both quite confused what you consider a feature. A feature is usually one vector dimension, but your understanding is, apparently, different.

**Comment by xxcheng0708** [comment]
record == row, feature == column, add row or add column ? Is it ok to add rows ? and how to do it?

**Comment by searchivarius** [comment]
@xxcheng0708 currently the index is static, you add rows and create an index.
