### ISSUE TITLE
Manual improvements & changes for the upcoming version

### ISSUE THREAD

**Issue by searchivarius** [searchivarius/nmslib#64]
1. Removal of HiddenClone() in Space
2. Recommendation to use DISABLE_COPY_AND_ASSIGN, 
3. **but** Now each space should have an explicit constructor
4. Object.id() function clarifications
5. No functions SetQueryTimeParamsInternal & GetQueryTimeParamNames in the Index function.
6. However, you have the function SetQueryTimeParams(...), CreateIndex(params), LoadIndex(string location), SaveIndex(string location);
7 GetParamOptional should now **ALWAYS** have a default value.
9. Index function ` DuplicateData() ` for methods that make data duplicates. 
10. In the test workflow specify that SetQueryTimeParams() is called before every execution. No need to call it inside the method any more!!!
11. Removal of an optional dimensionality parameter
12. Removal of some old ineffective methods, including: "permutation", "permutation_incsort",(permutation_incsort is superseeded by proj_incsort), permutation_vptree.
13. Strongly recommend to replace all pointers members with uniq_ptr.
14. Reminder about pmgr.checkParams()
15. this->ResetQueryTimeParams **must** be called by CreateIndex, or by the upper-level code. For some reason **this->** is needed.
16. SetQueryTimeParams shouldn't have required parameters without defaults.
21. By default, if no query-time parameters are specified each method will get a set of empty query-time parameters. Usually, this means that query-time parameters are reset to their default values. However, this behavior can be overriden (though this is not recommended) by method designers. Explain how it is possible to leave the parameter value unchanged.
17. Additional parameter IdType in Search()
18. dbScanFrac new query time parameter in PermBinVPTree
20. Command line parameters: space specifications remain the same. Method specification just accepts the name. If index is created from scratch index-time parameters are passed via createIndex. If the index is loaded from a location, one uses loadIndex instead. saveIndex specifies the location to save index. Each set of query-time parameters is specified separately using queryTimeParams.
20.5 SaveIndex won't be called by the framework, if the index doesn't exist **one gotcha** 
300 Explain why a user may encounter the following data mutation error:
```
016-04-22 00:49:54 main.cc:366 (RunExper) [INFO] Loading an index for test set id 0 using location: sw-graph-sift-ver7-NN=5,efConstruction=400_0
2016-04-22 00:49:54 small_world_rand_ver7.cc:918 (LoadIndex) [ERROR] Check failed: data_[nodeID]->id() == objID
2016-04-22 00:49:54 main.cc:434 (RunExper) [ERROR] Exception: Check failed: A previously saved index is apparently used with a different data set, a different data set split, and/or a different gold standard file! (unexpected object ID 204 for data element with ID 203 expected object ID: 203)
2016-04-22 00:49:54 main.cc:442 (RunExper) [FATAL] Failure due to an exception!
```
22. **To explicitly** specify a set of empty-query time parameters use --queryTimeParams ""
23. A new synonym  perm_bin_incsort
24. Describe precision of approximation in the manual
25. appendToResFile became a switch flag. Instead of printProgress, there is a switch noProgressBar
26. Cover options for the server & client.
27. Make sure you updated all the examples & texts where ToString() is mentioned.
28. small_world_rand got a synonym sw-graph *AND a new query-time par.:" efSearch (and an index-time parameter efConstruction)
29. Explain which methods support LoadIndex and SaveIndex
30. Intra-query ||-ism for sequential search: parameters multiThread & threadQty. Doesn't make sense to use for small data sets and/or very light weight distances.
31. VP-tree also has a random-restart parameter.
32. seq_search can also be named brute_force
33. Explain why we need to read data like this:
```
unique_ptr<DataFileInputState> inpState(space->ReadDataset(dataSet1, vExternIds1, sampleDataPrefix + dataSetFileName, maxNumRec));
space->UpdateParamsFromFile(*inpState);
```
34. Building with libraries installed in a non-standard location (**actually not everything is so simple, cmake file needs to be modified to be able to turnoff GSL & lshkit:
cmake . -DCMAKE_LIBRARY_PATH=/usr2/srchvrs/addPackages/lib/ -DCMAKE_INCLUDE_PATH=/usr2/srchvrs/addPackages/include  -DBoost_NO_SYSTEM_PATHS=true

35. Add docs for the word embedding space.

36.1 Building thrift. **Must use the exact same version!** See the guide here: https://thrift.apache.org/docs/BuildingFromSource On Ubuntu, first do
```
sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev libboost-thread-dev make
```
36.2 Regarding building the thrift:
```
You can also disable a lot of unnecessary crap by doing:
./configure --prefix=/home/srchvrs/addPackages --exec-prefix=/home/srchvrs/addPackages --without-java --without-erlang --without-nodejs --without-lua --without-python --without-php --without-ruby --without-haskell --without-go --without-d --with-cpp
```

Fixing a problem with boost:
```
 export BOOST_ROOT=/home/srchvrs/addPackagesSrc/boost_1_59_0
```

37. Building a new version on Windows, see an explanation there:

https://github.com/ot/path_decomposed_tries

38. Adding a reference to an earlier paper:

[PDF] Metrized Small World Properties Based Data Structure.
V Krylov, A Logvinov, A Ponomarenko, D Ponomarev - SEDE, 2008 - researchgate.net
100. Code style for newer Eclipse versions:

39. Setting white-space properties in the new Eclipse.

C / C++
    Click Window » Preferences
    Expand C/C++ » Code Style
    Click Formatter
    Click the New button to create a new profile, then OK to continue
    Click the Indentation tab
    Under General Settings, set Tab policy to: Spaces only
    Click OK ad nauseum to apply the changes.

40. The switch --maxCacheGSQty will be replaced with --maxCacheGSRelativeQty This options defines what fraction of the result set we store. By default, the value will be, e.g., 10. This would mean storing 10x as many entries as the number of result entries.

42. Describe a new (better) and more **configurable** plotting script `genplot_configurable.py`:
41.1 Limits for x & y
41.2 Optional title
41.3 Configurable name of the methodId field
41.4 Configurable axis names 
41.5 Configurable line types (can be anything PGFPLOTS package supports colors, line types, etc)

42. multi-threaded generation of gold-standard cache (should match the number of threads during experimentation)

43. Better gold-standard cache generation. There is now a coefficient K to memorize K * |size of the result| closest entries.

200. Explanation for the message:
```
2015-10-11 12:39:45 experiments.h:327 (Execute) [INFO] >>>> Computing effectiveness metrics for small_world_rand
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -2.09754 id = 140154 -> Apr: -2.11169 id = 140154 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.97406 id = 113850 -> Apr: -2.00505 id = 113850 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.88388 id = 102001 -> Apr: -1.89802 id = 102001 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.66678 id = 58445 -> Apr: -1.67824 id = 58445 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.65475 id = 76888 -> Apr: -1.66889 id = 76888 1 - ratio: -0.000202635 diff: -0.000221372
 2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.58057 id = 47669 -> Apr: -1.59471 id = 47669 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.52015 id = 65783 -> Apr: -1.49983 id = 14954 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.46885 id = 14954 -> Apr: -1.39462 id = 25564 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.45484 id = 90204 -> Apr: -1.37854 id = 120613 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.38047 id = 25564 -> Apr: -1.31906 id = 22051 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.36709 id = 120613 -> Apr: -1.20523 id = 101722 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.31842 id = 71704 -> Apr: -1.16612 id = 136738 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.3103 id = 22051 -> Apr: -1.10392 id = 52950 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.19109 id = 101722 -> Apr: -1.09269 id = 16190 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:71 (iterate) [INFO] Ex: -1.15736 id = 136738 -> Apr: -1.03483 id = 13878 1 - ratio: -0.000202635 diff: -0.000221372
2015-10-11 12:39:45 eval_metrics.h:75 (iterate) [FATAL] bug: the approximate query should not return objects that are closer to the query than object returned by (exact) sequential searching! Approx: -1.09269 id = 16190 Exact: -1.09247 id = 52950
```

**Comment by agangzz** [comment]
Hi, thank you for you great work for this fast and effective nmslib. I am looking forward for the upcoming version. so what's the release schedule of this upcoming version?

**Comment by searchivarius** [comment]
Hi, thank you for the kind words. The server version is basically ready (though some testing is needed), so it is a question of couple of months, but some testing is necessary (and the manual needs to be updated). A more advanced version will take longer to produces.

**Comment by agangzz** [comment]
Hi, searchivarius 
Thanks for your prompt reply. 
According my evaluation (index DB: 10 million * 50 dimension), the nmslib(SW-grap) is much better than other NNS method(such as FLANN, LSHKIT, E2LSH) in accuracy and efficiency, but the index building process of SW-grap is very expensive (for me, it cost me about 6 hours using 4 threads), which may limit the application of SW-grap.

So is there any solution to optimize the expense indexing cost of SW-grap? Do the Nmslib team have any suggestion or plan for this optimization?

Thanks.

**Comment by searchivarius** [comment]
Hi, thank you for the evaluation. Indexing time is, indeed, a concern, so we should look into ways of improving it. So, this is, indeed, a great feature request and there are some ways that can potentially speed up indexing quite a bit. It will not happen very soon though (unless somebody helps us). One quick solution is to merely add more threads (e.g., on Amazon you can have up to 18 real cores). Indexing scales well with the number of threads, so with 18 cores, it will probably take you a bit longer than an hour. We should, probably, look into indexing using a GPU as well.

**Comment by searchivarius** [comment]
Hi @agangzz , on a second thought, two things can be done very soon (and some immediately):
1) There are CPUs with a lot of cores. Amazon AWS servers have up to 18 real cores. Indexing scales well with the number of threads. So, indexing of 10 billion will take more like 1.5 hour.
2) Indexing slows down as the collection size increases. It is usually beneficial to index the largest data set as possible, because improvement in efficiency usually increases (due to sublinearity). However, for some data sets, in particular, for embeddings, the search time grows nearly linearly. So, in fact, by splitting a collection in say 5 million chunks and indexing each chunk separately, you can sometimes improve the overall indexing time dramatically. The retrieval time will be a bit worse, but likely it will not be more than 20-30% increase. In an upcoming release, we have a version that splits data transparently, i.e., you don't have to maintain many copies yourself.
3) You can play with parameters. Again, in the upcoming version, there is more flexibility and both indexing/retrieval improves a bit (by about 30% on embedding-like data).
So, will these kind of improvements sufficient to get things going? Also, it takes many days to compute embeddings. Using hours to build an index doesn't sound like a huge overhead, does it?

**Comment by agangzz** [comment]
Hi, searchivarius 
I have run my code in a server with 24 cores @ 1.9GHz
(1) for indexing DB with 10 million * 50 dimension, the indexing time decreased from 6 hours(4 threads) to 1.3 hours(24 threads).
(2) but our target indexing DB may be larger than 200 million. In the algorithm verification phase, the indexing time with several days may be very expensive.

Splitting data is a good idea, I will try it.  And also I'm looking forward for the upcoming release.

By the way, I have two questions about Small-word grap algorithm:
(1) When Small-world index is completed(may cost several hours or days), I want to save the index to avoid rebuild it. Is there any convenient solution to save index structure( Index<float>*   indexSmallWorld ) ?
(2) There are several parameters of small-word-grap algorithm, such as NN, initIndexAttempts, initSearchAttempts, Could you explain their meaning and influence for the recall/accuracy? When the indexing DB is larger than 200 million (50 dimensions), Could you provide me some suggestions?

Thanks a lot

**Comment by searchivarius** [comment]
Hi, @agangzz 

(1) Great! 
(2) For fast in-memory search, you would need to split among machines anyways. I think it may not be impossible to have 20-30 million per node.

Regarding your questions. Why don't we continue our discussion via e-mail (leo at boytsov.info).
(1) Yes, there is. It's not very fast, but still muuuch faster than recreating it :-)
(2) Unfortunately, not. In theory, you can easily add entries to SW-graph, but the framework doesn't support it. Do you need replacing old entries?
(3) I will explain.
