### ISSUE TITLE
Hierarchical NSW

### ISSUE THREAD

**Issue by musicformellons** [searchivarius/nmslib#85]
This article:
http://arxiv.org/abs/1603.09320

mentions: "An implementation of the Hierarchical NSW algorithm presented in this paper is also will
be distributed as a part of the open source Non Metric Space Library." 

So I was wondering if you could an indication when that might be as it looks like this is not yet the case.

**Comment by yurymalkov** [comment]
Hierarchical NSW (or HNSW) was added to the pserv branch (https://github.com/searchivarius/nmslib/tree/pserv) less than a day ago. It is functional, but does not have any documentation yet. By the end of this week we are going to add it to ann bechnmark.
And as far as I know @searchivarius is going to make soon a major merging (pserv has many new features), with the documentation updates, so Hierarchical NSW will go into master.

**Comment by musicformellons** [comment]
Wow, that's cool! Thanks for your swift reply.

**Comment by searchivarius** [comment]
That was easy :-) I will update docs very soon.
